import { StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';
import { DIMENS } from '../../../core/constants/dimensions';

const styles = StyleSheet.create({
 wrapper: {
  marginLeft: 4,
  marginRight: 4,
  marginTop: 4,
  marginBottom: 4,
 },
 card: {
  backgroundColor: '#fff',
  borderRadius: 10,
  paddingLeft: 8,
  paddingRight: 8,
  paddingTop: 16,
  paddingBottom: 16,
 },
 summaryRow: {
  flexDirection: 'row',
  alignItems: 'center',
 },
 sideCol: {
  flex: 1,
 },
 sideColRight: {
  flex: 1,
  alignItems: 'flex-end',
 },
 amountRowLeft: {
  flexDirection: 'row',
  alignItems: 'center',
 },
 amountRowRight: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-end',
 },
 coinText: {
  marginRight: 8,
  color: COLORS.colorPrimaryIntLetter,
  fontSize: DIMENS.numberItemText,
  fontFamily: 'AriaRounded',
 },
 amountText: {
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: DIMENS.bigTextNumbers,
  fontFamily: 'ArialRoundedRegular',
 },
 subRowLeft: {
  marginTop: 6,
  flexDirection: 'row',
  alignItems: 'center',
 },
 subRowRight: {
  marginTop: 6,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-end',
 },
 accountName: {
  color: COLORS.colorPrimaryClearLetter,
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
  flexShrink: 1,
 },
 rateText: {
  color: COLORS.colorPrimaryClearLetter,
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
  textAlign: 'right',
  flexShrink: 1,
 },
 typeImage: {
  width: 56,
  height: 62,
  resizeMode: 'contain',
  marginHorizontal: 8,
 },
 pendingIconLeft: {
  width: 20,
  height: 22,
  opacity: 0.6,
  marginRight: 8,
  resizeMode: 'contain',
 },
 pendingIconRight: {
  width: 20,
  height: 22,
  opacity: 0.6,
  marginLeft: 8,
  resizeMode: 'contain',
 },
 expanded: {
  marginTop: 8,
 },
 affectRow: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: 2,
 },
 affectColLeft: {
  flex: 1,
  alignItems: 'flex-start',
 },
 affectColRight: {
  flex: 1,
  alignItems: 'flex-end',
 },
 affectIcon: {
  width: 25,
  height: 20,
  opacity: 0.9,
  resizeMode: 'contain',
 },
 stateRow: {
  marginTop: 22,
  marginLeft: 8,
  marginRight: 8,
  height: 40,
  flexDirection: 'row',
  alignItems: 'center',
 },
 stateSideLeft: {
  flex: 1.6,
  alignItems: 'flex-start',
  justifyContent: 'center',
 },
 stateSideRight: {
  flex: 1.6,
  alignItems: 'flex-end',
  justifyContent: 'center',
 },
 stateCenter: {
  flex: 3.2,
  alignItems: 'center',
  justifyContent: 'center',
 },
 changeStatesInline: {
  width: '100%',
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
 },
 changeStatesArrowImg: {
  width: 30,
  height: 30,
  opacity: 0.8,
  resizeMode: 'contain',
 },
 stateIcon: {
  width: 35,
  height: 35,
  resizeMode: 'contain',
 },
 changeStatesText: {
  color: COLORS.word_clear_clear,
  fontSize: DIMENS.textDetailBottom,
  fontFamily: 'OpenSansRegular',
  textAlign: 'center',
  marginHorizontal: 10,
  flexShrink: 1,
 },
 infoRow: {
  marginTop: 18,
  flexDirection: 'row',
  alignItems: 'center',
 },
 dateWrap: {
  flex: 1,
  flexDirection: 'row',
  alignItems: 'center',
 },
 dateIcon: {
  width: 22,
  height: 22,
  opacity: 0.8,
  resizeMode: 'contain',
 },
 dateText: {
  marginLeft: 8,
  color: COLORS.word,
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
 },
 moreInfoWrap: {
  flex: 1.2,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-end',
  height: 40,
 },
 infoIcon: {
  width: 22,
  height: 22,
  opacity: 0.8,
  marginRight: 8,
  resizeMode: 'contain',
 },
 moreInfoText: {
  color: COLORS.word,
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
 },
 infoDialogBackdrop: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.52)',
  justifyContent: 'center',
  alignItems: 'center',
  padding: 10,
 },
 infoDialogCard: {
  width: '100%',
  maxWidth: 520,
  borderRadius: 12,
  backgroundColor: '#f3f2f7',
  overflow: 'hidden',
  margin: 8,
 },
 infoDialogContent: {
  marginTop: DIMENS.dialogMarginTop,
  marginBottom: DIMENS.dialogMarginBottom,
 },
 infoDialogHeader: {
  paddingTop: 8,
  paddingBottom: 4,
  paddingHorizontal: DIMENS.dialogMarginLeft,
  alignItems: 'center',
 },
 infoDialogType: {
  color: '#4f4677',
  height: 35,
  textAlignVertical: 'center',
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansBold',
 },
 infoDialogSummaryCard: {
  position: 'relative',
  marginHorizontal: 8,
  marginBottom: 8,
  height: 105,
  borderRadius: 10,
  paddingBottom: 20,
 },
 infoDialogIncludedItem: {
  backgroundColor: '#fcfcfd',
  borderRadius: 10,
  paddingLeft: 8,
  paddingRight: 8,
  paddingTop: 16,
  paddingBottom: 16,
 },
 infoDialogSummarySide: {
  flex: 1,
 },
 infoDialogSummarySideRight: {
  flex: 1.1,
  alignItems: 'flex-end',
 },
 infoDialogAmountRowLeft: {
  flexDirection: 'row',
  alignItems: 'center',
 },
 infoDialogAmountRowRight: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-end',
 },
 infoDialogCoinText: {
  marginRight: 8,
  color: COLORS.colorPrimaryIntLetter,
  fontSize: DIMENS.numberItemText,
  fontFamily: 'AriaRounded',
 },
 infoDialogAmountText: {
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: DIMENS.bigTextNumbers,
  fontFamily: 'ArialRoundedRegular',
 },
 infoDialogSubRowLeft: {
  marginTop: 6,
  flexDirection: 'row',
  alignItems: 'center',
 },
 infoDialogSubRowRight: {
  marginTop: 6,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-end',
 },
 infoDialogSub: {
  color: '#8f86aa',
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
 },
 infoDialogSubRateCode: {
  color: '#8f86aa',
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
  marginRight: 4,
  textTransform: 'uppercase',
 },
 infoDialogSubRateOne: {
  color: '#8f86aa',
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
  marginRight: 4,
 },
 infoDialogSubRateEq: {
  color: '#8f86aa',
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
  marginRight: 4,
 },
 infoDialogSubRateValue: {
  color: '#8f86aa',
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
 },
 infoDialogTypeImage: {
  width: 56,
  height: 62,
  resizeMode: 'contain',
  marginHorizontal: 8,
 },
 infoDialogAffectInWrap: {
  position: 'absolute',
  left: 0,
  bottom: 0,
  width: '50%',
  alignItems: 'flex-start',
 },
 infoDialogAffectOutWrap: {
  position: 'absolute',
  right: 0,
  bottom: 0,
  width: '50%',
  alignItems: 'flex-end',
 },
 infoDialogAffectIcon: {
  width: 25,
  height: 20,
  resizeMode: 'contain',
 },
 infoDialogMetaRow: {
  minHeight: 35,
  flexDirection: 'row',
  alignItems: 'center',
  marginLeft: DIMENS.dialogMarginLeft,
  marginRight: DIMENS.dialogMarginRight,
  marginTop: 4,
 },
 infoDialogMetaRowFirst: {
  paddingTop: 4,
 },
 infoDialogMetaIconCol: {
  width: 30,
  alignItems: 'center',
  justifyContent: 'center',
  },
 infoDialogMetaValueCol: {
  flex: 1,
  justifyContent: 'center',
  marginLeft: 8,
 },
 infoDialogMetaIcon: {
  width: 22,
  height: 22,
  resizeMode: 'contain',
  opacity: 0.9,
 },
 infoDialogMetaText: {
  color: '#615886',
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
 },
 infoDialogActions: {
  marginTop: 16,
  paddingHorizontal: 0,
  paddingBottom: 0,
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
 },
 infoDialogActionBtn: {
  width: '50%',
  height: 42,
  alignItems: 'center',
  justifyContent: 'center',
 },
 infoDialogActionIcon: {
  width: 40,
  height: 40,
  padding: 9,
  resizeMode: 'contain',
  opacity: 0.45,
 },
});

export default styles;
