import { StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';
import { CHECK_DIALOG_SHARED } from './checkDialogShared';

const styles = StyleSheet.create({
  backdrop: CHECK_DIALOG_SHARED.backdrop,
  card: CHECK_DIALOG_SHARED.card,
  title: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 17,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'center',
    marginBottom: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  summaryLabelPrimary: {
    flex: 1,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 18,
    fontFamily: 'ArialRoundedRegular',
    paddingRight: 12,
  },
  summaryValuePrimary: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 20,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'right',
  },
  summaryLabelSecondary: {
    flex: 1,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
    paddingRight: 12,
  },
  summaryValueSecondary: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
    textAlign: 'right',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  inputLabel: {
    flex: 1,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
    paddingRight: 12,
  },
  input: {
    flex: 1,
    minHeight: 38,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    color: COLORS.word,
    paddingHorizontal: 8,
    textAlign: 'right',
    fontSize: 17,
    fontFamily: 'OpenSansLight',
  },
  messageError: {
    color: '#b77516',
    fontSize: 14,
    fontFamily: 'OpenSansRegular',
    marginBottom: 4,
  },
  errorBanner: {
    marginTop: 18,
    borderRadius: 8,
    backgroundColor: '#E2AAA7',
    paddingLeft: 12,
    paddingRight: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  errorBannerText: {
    flex: 1,
    color: '#5B231B',
    fontSize: 16,
    lineHeight: 22,

    fontFamily: 'OpenSansRegular',
  },
  errorBannerIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 22,
    backgroundColor: '#6D1D15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorBannerIcon: {
    color: '#fff',
    fontSize: 25,
    fontFamily: 'OpenSansBold',
  },
  sectionBlock: {
    marginTop: 18,
  },
  accountSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  accountSectionLabel: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
  },
  accountSectionName: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 16,
    fontFamily: 'OpenSansBold',
  },
  breakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  percentInputWrap: {
    width: 100,
    minHeight: 38,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  percentSymbol: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
    marginRight: 6,
  },
  breakdownInput: {
    flex: 1,
    minHeight: 38,
    color: COLORS.word,
    fontSize: 18,
    fontFamily: 'OpenSansLight',
    textAlign: 'left',
  },
  adminInput: {
    width: 100,
    minHeight: 38,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    color: COLORS.word,
    fontSize: 18,
    fontFamily: 'OpenSansLight',
    textAlign: 'left',
    paddingHorizontal: 12,
    marginLeft: 10,
  },
  breakdownAmount: {
    flex: 1,
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 19,
    fontFamily: 'OpenSansLight',
    textAlign: 'right',
    marginLeft: 12,
  },
  boxRow: {
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  boxLeft: {
    flex: 1,
    paddingRight: 12,
  },
  boxName: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 16,
    fontFamily: 'OpenSansBold',
    marginTop: 2,
  },
  boxAmount: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 18,
    fontFamily: 'OpenSansLight',
    textAlign: 'right',
    marginLeft: 12,
    paddingTop: 18,
  },
  actions: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionsSingle: {
    justifyContent: 'center',
  },
  cancelBtn: {
    flex: 1,
    minHeight: CHECK_DIALOG_SHARED.actionButtonHeight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 17,
    fontFamily: 'ArialRoundedRegular',
  },
  saveBtn: {
    flex: 1,
    minHeight: CHECK_DIALOG_SHARED.actionButtonHeight,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryChange,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginLeft: 18,
  },
  saveText: {
    color: COLORS.white,
    fontSize: 18,
    fontFamily: 'OpenSansBold',
  },
});

export default styles;
