import { StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';
import { CHECK_DIALOG_SHARED } from './checkDialogShared';

const styles = StyleSheet.create({
  backdrop: CHECK_DIALOG_SHARED.backdrop,
  card: {
    ...CHECK_DIALOG_SHARED.card,
    borderRadius: 10,
  },
  title: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 19,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
    marginBottom: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  summaryLabelPrimary: {
    flex: 1,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 18,
    fontFamily: 'arialroundedreg',
    paddingRight: 12,
  },
  summaryValuePrimary: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 21,
    fontFamily: 'arialroundedreg',
    textAlign: 'right',
  },
  summaryLabelSecondary: {
    flex: 1,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
    paddingRight: 12,
  },
  summaryValueSecondary: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
    textAlign: 'right',
  },
  rejectedRow: {
    marginBottom: 2,
  },
  rejectedLabel: {
    color: '#b77516',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  inputLabel: {
    flex: 1,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
    paddingRight: 12,
  },
  input: {
    flex: 1,
    minHeight: 40,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    color: COLORS.word,
    paddingHorizontal: 10,
    textAlign: 'right',
    fontSize: 16,
    fontFamily: 'OpenSansLight',
  },
  messageOk: {
    color: '#6d8f34',
    fontSize: 14,
    fontFamily: 'OpenSansRegular',
    marginBottom: 8,
  },
  messageError: {
    color: '#b77516',
    fontSize: 14,
    fontFamily: 'OpenSansRegular',
    marginBottom: 8,
  },
  errorBanner: {
    marginTop: 18,
    borderRadius: 10,
    backgroundColor: '#E2AAA7',
    paddingLeft: 12,
    paddingRight: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  errorBannerText: {
    flex: 1,
    color: '#5B231B',
    fontSize: 15,
    lineHeight: 20,
    fontFamily: 'OpenSansRegular',
    paddingRight: 12,
  },
  errorBannerIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#6D1D15',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorBannerIcon: {
    color: '#fff',
    fontSize: 21,
    fontFamily: 'OpenSansBold',
    lineHeight: 24,
  },
  successBanner: {
    marginTop: 12,
    borderRadius: 8,
    backgroundColor: '#E8F1E8',
    paddingLeft: 10,
    paddingRight: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  successBannerText: {
    flex: 1,
    color: '#3F7443',
    fontSize: 16,
    lineHeight: 21,
    fontFamily: 'OpenSansRegular',
    paddingRight: 6,
  },
  successBannerIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#28502B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  successBannerIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  commissionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
  },
  commissionLeft: {
    flex: 0.8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commissionIcon: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
  },
  commissionLabel: {
    width: 25,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
  },
  commissionPercentValue: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 20,
    fontFamily: 'OpenSansLight',
    width: 46,
    marginBottom: 2,
    textAlign: 'center',
  },
  commissionPercent: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 20,
    fontFamily: 'ArialRoundedRegular',
    marginLeft: 4,
    marginTop: 4,

  },
  commissionAmountWrap: {
    flex: 1.1,
    minHeight: 35,
    justifyContent: 'center',
    paddingLeft: 20,
  },
  commissionAmountValue: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 18,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'right',
    paddingRight: 8,
  },
  accountRow1: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 14,
  },
  accountRow2: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  accountLeft: {
    flex: 1.5,
    paddingRight: 12,
  },
  accountAmountWrap: {
    flex: 1.1,
    justifyContent: 'center',
    paddingLeft: 20,
    minHeight: 52,
  },
  accountAmountValue: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 18,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'right',
    paddingRight: 8,
  },
  accountLabel: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
    marginBottom: 2,
  },
  accountName: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 16,
    marginTop: 2,
    fontFamily: 'ArialRoundedRegular',
  },
  messageSubtle: {
    marginTop: 10,
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 13,
    fontFamily: 'OpenSansLight',
  },
  actions: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  actionsSingle: {
    justifyContent: 'center',
  },
  cancelBtn: {
    flex: 1,
    minWidth: 110,
    minHeight: CHECK_DIALOG_SHARED.actionButtonHeight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 18,
    fontFamily: 'ArialRoundedRegular',
  },
  saveBtn: {
    minWidth: 180,
    minHeight: CHECK_DIALOG_SHARED.actionButtonHeight,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryChange,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  saveText: {
    color: COLORS.white,
    fontSize: 17,
    fontFamily: 'OpenSansBold',
  },
});

export default styles;
