import { StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 24,
  },
  scrollContent: {
    paddingBottom: 34,
  },
  totalCard: {
    height: 60,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  totalIconWrap: {
    flex: 0.4,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  totalDivider: {
    width: 1,
    alignSelf: 'stretch',
    borderLeftWidth: 1,
    borderColor: COLORS.colorPrimaryClearLetter,
    borderStyle: 'dashed',
    marginLeft: 4,
    marginRight: 4,
    marginTop: 8,
    marginBottom: 8,
  },
  totalInput: {
    flex: 1,
    height: '100%',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 26,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'left',
  },
  totalInputWrap: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    paddingLeft: 6,
    paddingTop: 4,
    paddingRight: 12,
  },
  totalPlaceholder: {
    position: 'absolute',
    left: 6,
    right: 12,
    color: COLORS.colorPrimaryClear,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
  },
  totalFlag: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    opacity: 0.8,
  },
  section: {
    marginTop: 16,
    gap: 16,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  percentBox: {
    flex: 1,
    height: 42,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  percentIcon: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
    marginLeft: 8,
    marginRight: 6,
  },
  percentInput: {
    flex: 0.8,
    height: 35,
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
    textAlign: 'center',
    paddingLeft: 4,
    paddingRight: 8,
  },
  percentText: {
    marginLeft: 6,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 22,
    fontFamily: 'OpenSansLight',
    marginRight: 8,
  },
  amountBox: {
    flex: 1.1,
    height: 42,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryClear3,
    marginLeft: 12,
    justifyContent: 'center',
    paddingLeft: 8,
    paddingTop: 1,
  },
  amountValue: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 22,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'right',
    paddingRight: 8,
  },
  accountSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 0,
    marginTop: 8,
    marginLeft: 12,
    marginRight: 12,
  },
  accountSelectorIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryIntLetter2,
    opacity: 0.8,
    marginRight: 6,
  },
  accountSelectorText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 18,
    fontFamily: 'OpenSansLight',
  },
  accountSelectorPlaceholder: {
    color: COLORS.colorPrimaryClearLetter,
    fontFamily: 'OpenSansLight',
  },
  accountSelectorArrow: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryIntLetter2,
    opacity: 0.7,
    marginLeft: 8,
  },
  amountWideBox: {
    height: 52,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryClear3,
    marginLeft: 12,
    marginRight: 12,
    paddingHorizontal: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  amountWidePrefix: {
    fontSize: 28,
    fontFamily: 'ArialRoundedRegular',
    marginLeft: 8,
    marginTop: 6,
    marginRight: 8,
  },
  amountWidePrefixPositive: {
    color: COLORS.colorPrimaryClearLetter,
  },
  amountWidePrefixNegative: {
    color: COLORS.colorPrimaryClearLetter,
  },
  amountWideText: {
    flex: 1,
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 19,
    fontFamily: 'ArialRoundedRegular',
    paddingRight: 12,
  },
  amountWidePlaceholder: {
    color: COLORS.colorPrimaryClear,
    fontFamily: 'OpenSansLight',
  },
  actionsRow: {
    height: 45,
    marginTop: 22,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 12,
    marginRight: 12,
  },
  actionHalf: {
    flex: 0.5,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearBtn: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearIcon: {
    width: 85,
    height: 35,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryClearLetter,
    opacity: 0.4,
  },
  clearText: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 17,
    fontFamily: 'OpenSansRegular',
  },
  createBtn: {
    alignSelf: 'center',
    minWidth: 0,
    minHeight: 0,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryChange,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
  },
  createIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    marginRight: 10,
  },
  createText: {
    color: COLORS.white,
    fontSize: 17,
    fontFamily: 'OpenSansRegular',
  },
  helperText: {
    color: COLORS.word_clear,
    fontSize: 14,
    fontFamily: 'OpenSansLight',
  },
  pickerCard: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 380,
    borderRadius: 14,
    backgroundColor: COLORS.background_dialog,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
  },
  pickerBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.22)',
    paddingHorizontal: 18,
  },
  pickerTitle: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
    marginBottom: 12,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInput: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    color: COLORS.colorPrimaryDarkLetter,
    paddingHorizontal: 12,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
  },
  pickerCloseInlineBtn: {
    width: 36,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  pickerCloseInlineText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 24,
    lineHeight: 24,
    fontFamily: 'ArialRoundedRegular',
  },
  pickerList: {
    marginTop: 12,
    maxHeight: 340,
  },
  pickerItem: {
    borderRadius: 8,
    backgroundColor: COLORS.white,
    marginBottom: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  pickerItemInner: {
    minHeight: 55,
    flexDirection: 'row',
    alignItems: 'center',
  },
  pickerItemCircle: {
    width: 40,
    height: 40,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  pickerItemCircleImg: {
    position: 'absolute',
    width: 42,
    height: 42,
    resizeMode: 'contain',
  },
  pickerItemCircleText: {
    color: COLORS.white,
    fontSize: 20,
    fontFamily: 'OpenSansRegular',
  },
  pickerItemMainInfo: {
    flex: 1,
    marginLeft: 4,
    paddingRight: 4,
  },
  pickerItemText: {
    color: COLORS.word,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
  },
  pickerItemCategory: {
    marginTop: 2,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 13,
    fontFamily: 'OpenSansLight',
    textTransform: 'lowercase',
  },
  pickerEmpty: {
    paddingVertical: 18,
    alignItems: 'center',
  },
  pickerEmptyText: {
    color: COLORS.word_clear,
    fontSize: 15,
    fontFamily: 'OpenSansLight',
    textAlign: 'center',
  },
});

export default styles;
