import { Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';

const isWeb = Platform.OS === 'web';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  topBar: {
    height: isWeb ? 48 : 98,
    paddingTop: isWeb ? 0 : 37,
    paddingHorizontal: 22,
    backgroundColor: COLORS.colorPrimaryChange,
    flexDirection: 'row',
    alignItems: 'center',
  },
  leftButton: {
    minWidth: 34,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarArrow: {
    color: COLORS.topBarText,
    fontSize: isWeb ? 24 : 30,
    marginRight: isWeb ? 18 : 22,
  },
  topBarTitle: {
    flex: 1,
    color: COLORS.topBarText,
    fontSize: isWeb ? 18 : 22,
    fontFamily: 'OpenSansRegular',
  },
  topBarSave: {
    width: isWeb ? 34 : 40,
    height: isWeb ? 30 : 35,
    resizeMode: 'contain',
  },
  scrollContent: {
    paddingBottom: 320,
  },
  formWrap: {
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  typeSwitchWrap: {
    alignItems: 'center',
    marginTop: 8,
  },
  typeSwitch: {
    width: 300,
    height: 28,
    borderRadius: 10,
    backgroundColor: COLORS.colorPrimaryClear2,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  typeSwitchHalf: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeSwitchHalfActive: {
    backgroundColor: COLORS.colorPrimaryChange,
  },
  typeSwitchText: {
    color: COLORS.topBarText,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
  },
  typeSwitchTextInactive: {
    color: COLORS.white2,
  },
  amountCard: {
    height: 65,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    marginTop: 16,
    marginHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  amountCardDisabled: {
    backgroundColor: COLORS.colorPrimaryClear3,
  },
  coinButton: {
    flex: 1.4,
    height: '75%',
    borderRadius: 16,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 12,
    paddingRight: 12,
    marginLeft: 4,
  },
  coinFlag: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    opacity: 0.85,
  },
  coinLabel: {
    marginLeft: 16,
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 24,
    marginTop: 6,
    fontFamily: 'ArialRoundedRegular',
  },
  amountDivider: {
    width: 1,
    alignSelf: 'stretch',
    borderLeftWidth: 1,
    borderStyle: 'dashed',
    borderColor: COLORS.colorPrimaryClearLetter,
    marginVertical: 10,
    marginHorizontal: 6,
  },
  amountInputWrap: {
    flex: 2.15,
    height: '100%',
    justifyContent: 'center',
    paddingLeft: 8,
    paddingRight: 12,
  },
  amountInput: {
    height: '100%',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 27,
    fontFamily: 'ArialRoundedRegular',
  },
  amountInputDisabled: {
    color: COLORS.colorPrimaryDarkLetter,
  },
  methodSwitchWrap: {
    alignItems: 'flex-end',
    marginTop: 16,
    marginRight: 20,
  },
  methodSwitch: {
    width: 140,
    height: 25,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryClear3,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  methodHalf: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  methodHalfActive: {
    backgroundColor: COLORS.white,
  },
  methodText: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 20,
    fontFamily: 'OpenSansRegular',
  },
  methodTextActive: {
    color: COLORS.colorPrimaryClearLetter,
  },
  fieldGroup: {
    marginTop: 8,
  },
  accountHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
    marginBottom: 10,
    marginTop: 8,
  },
  accountIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
    opacity: 0.5,
    marginRight: 6,
  },
  accountHeaderText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 18,
    marginRight: 16,
    fontFamily: 'OpenSansLight',
  },
  accountHeaderPlaceholder: {
    color: COLORS.colorPrimaryClear,
    minWidth: 95,
  },
  accountHeaderArrow: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryIntLetter2,
    opacity: 0.7,
    marginRight: 8,
  },
  moneyRow: {
    height: 42,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryClear3,
    marginHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 8,
  },
  moneyRowActive: {
    backgroundColor: COLORS.white,
  },
  signText: {
    width: 20,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 28,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'center',
  },
  moneyInput: {
    flex: 1,
    height: '100%',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 24,
    marginTop: 4,
    fontFamily: 'ArialRoundedRegular',
    paddingLeft: 8,
  },
  moneyInputDisabled: {
    color: COLORS.colorPrimaryDarkLetter,
  },
  stateButton: {
    width: 40,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 8,
  },
  stateIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
    opacity: 0.35,
  },
  dualMoneyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
  },
  percentBox: {
    flex: 1.5,
    height: 42,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryClear3,
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 4,
  },
  percentBoxActive: {
    backgroundColor: COLORS.white,
  },
  percentPrefix: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 20,
    fontFamily: 'ArialRoundedRegular',
    paddingLeft: 12,
  },
  percentInput: {
    flex: 1,
    height: '100%',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 20,
    fontFamily: 'OpenSansLight',
    paddingLeft: 8,
    paddingBottom: 6,
  },
  percentInputDisabled: {
    color: COLORS.colorPrimaryDarkLetter,
  },
  dualAmountBox: {
    flex: 2,
    height: 42,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryClear3,
    marginLeft: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 8,

  },
  dualAmountBoxActive: {
    backgroundColor: COLORS.white,
  },
  dualAmountInput: {
    flex: 1,
    height: '100%',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 24,
    fontFamily: 'ArialRoundedRegular',
    paddingLeft: 8,
    marginTop: 4,

  },
  dualAmountInputDisabled: {
    color: COLORS.colorPrimaryDarkLetter,
  },
  clientAddRow: {
    marginTop: 30,
    marginHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  clientAddIcon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    marginRight: 10,
  },
  clientAddText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
  },
  actionsRow: {
    height: 45,
    marginTop: 22,
    marginHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionHalf: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearBtn: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  clearIcon: {
    width: 85,
    height: 35,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryClearLetter,
    opacity: 0.4,
  },
  sheetWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  sheetBody: {
    flex: 1,
    backgroundColor: COLORS.background_bottom_sheet,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 6,
  },
  listContent: {
    paddingHorizontal: 6,
    paddingTop: 6,
    paddingBottom: 28,
  },
  reportCard: {
    marginHorizontal: 2,
    marginTop: 4,
    marginBottom: 4,
    paddingHorizontal: 8,
    paddingVertical: 16,
    borderRadius: 8,
    backgroundColor: COLORS.white,
  },
  reportRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  reportName: {
    flex: 1.1,
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 18,
    fontFamily: 'OpenSansLight',
  },
  reportCommissionSpacer: {
    width: 54,
  },
  reportSignWrap: {
    width: 24,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportSign: {
    width: 24,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 17,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'center',
  },
  reportAmountWrap: {
    flex: 1.3,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  reportStateIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    position: 'absolute',
    left: 18,
    top: -20,
    opacity: 0.45,
  },
  reportStateButton: {
    width: 28,
    height: 28,
  },
  reportAmount: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 24,
    fontFamily: 'ArialRoundedRegular',
    marginRight: 8,
  },
  reportFlag: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    opacity: 0.85,
    marginBottom: 6,
  },
  reportSmallRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginHorizontal: 4,
  },
  reportMetaName: {
    flex: 1.1,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
  },
  reportMetaCommissionWrap: {
    width: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportMetaCommission: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'ArialRoundedRegular',
  },
  reportMetaPercent: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 15,
    fontFamily: 'OpenSansLight',
  },
  reportMetaAmountWrap: {
    flex: 1.3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  reportMetaAmount: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 17,
    fontFamily: 'ArialRoundedRegular',
    marginRight: 8,
  },
  reportDivider: {
    height: 1,
    marginTop: 12,
    marginBottom: 12,
    marginHorizontal: 12,
    backgroundColor: '#DDD8EE',
  },
  reportBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  reportExpandedRow: {
    marginTop: 14,
    marginHorizontal: 4,
    paddingTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportExpandedDateWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  reportExpandedDateIcon: {
    width: 22,
    height: 22,
    opacity: 0.8,
    resizeMode: 'contain',
  },
  reportExpandedDate: {
    marginLeft: 8,
    color: COLORS.word,
    fontSize: 16,
    fontFamily: 'OpenSansRegular',
  },
  reportMoreInfoRow: {
    flex: 1.1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: 40,
  },
  reportMoreInfoIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    marginRight: 6,
    opacity: 0.8,
  },
  reportMoreInfoText: {
    color: COLORS.word,
    fontSize: 16,
    fontFamily: 'OpenSansRegular',
  },
  emptyWrap: {
    marginTop: 30,
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  emptyText: {
    color: COLORS.word_clear,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
  },
  errorText: {
    color: '#8d4d62',
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
  },
  retryBtn: {
    marginTop: 10,
    backgroundColor: COLORS.colorPrimaryChange,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  retryText: {
    color: COLORS.white,
    fontFamily: 'OpenSansRegular',
  },
  pickerBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.22)',
    paddingHorizontal: 18,
  },
  emitidaPickerBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.04)',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  emitidaPickerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
  },
  emitidaPickerBackdropInline: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
  },
  coinPickerBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.08)',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  pickerCard: {
    width: '100%',
    borderRadius: 14,
    backgroundColor: COLORS.background_dialog,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
  },
  coinPickerCard: {
    position: 'absolute',
    left: 20,
    top: 160,
    width: 196,
    maxHeight: 430,
    borderRadius: 22,
    backgroundColor: COLORS.backgroundA,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 10,
  },
  emitidaPickerCard: {
    position: 'absolute',
    width: 262,
    maxHeight: 260,
    borderRadius: 22,
    backgroundColor: COLORS.white,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 12,
  },
  pickerTitle: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
    marginBottom: 12,
  },
  pickerSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pickerSearchInput: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    color: COLORS.colorPrimaryDarkLetter,
    paddingHorizontal: 12,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
  },
  pickerCloseInlineBtn: {
    width: 36,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  pickerCloseInlineText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 24,
    lineHeight: 24,
    fontFamily: 'ArialRoundedRegular',
  },
  pickerList: {
    marginTop: 12,
    maxHeight: 340,
  },
  emitidaPickerList: {
    maxHeight: 260,
  },
  coinPickerList: {
    maxHeight: 430,
  },
  coinPickerRow: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  coinPickerFlag: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
    marginRight: 10,
  },
  coinPickerText: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 20,
    lineHeight: 24,
    fontFamily: 'ArialRoundedRegular',
  },
  coinPickerEmpty: {
    minHeight: 150,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  coinPickerEmptyText: {
    color: COLORS.word_clear,
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'OpenSansRegular',
  },
  pickerItem: {
    borderRadius: 8,
    backgroundColor: COLORS.white,
    marginBottom: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  emitidaPickerItem: {
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  pickerItemRow: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
  },
  pickerAvatar: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    position: 'relative',
  },
  pickerAvatarBg: {
    position: 'absolute',
    width: 42,
    height: 42,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryClearLetter,
  },
  pickerAvatarText: {
    color: COLORS.white,
    fontSize: 20,
    fontFamily: 'OpenSansRegular',
  },
  pickerItemMainInfo: {
    flex: 1,
  },
  pickerItemText: {
    color: COLORS.word,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
  },
  pickerItemSubText: {
    marginTop: 2,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 13,
    fontFamily: 'OpenSansLight',
  },
});

export default styles;
