import { Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';
import { DIMENS } from '../../../core/constants/dimensions';

const isWeb = Platform.OS === 'web';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  tabsRow: {
    height: isWeb ? 48 : 58,
    flexDirection: 'row',
    backgroundColor: COLORS.colorPrimaryDarkChange,
  },
  tabBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
    paddingHorizontal: 8,
  },
  tabBtnActive: {
    borderBottomColor: COLORS.white,
  },
  tabText: {
    color: '#8f9088',
    fontSize: DIMENS.numberItemText,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
  },
  tabTextActive: {
    color: COLORS.white,
  },
  content: {
    flex: 1,
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyText: {
    color: COLORS.colorPrimaryIntLetter2,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
  },
  retryBtn: {
    marginTop: 14,
    minWidth: 120,
    minHeight: 36,
    borderRadius: 8,
    backgroundColor: COLORS.colorDialogButton,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  retryText: {
    color: COLORS.white,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
  },
  card: {
    marginHorizontal: 14,
    marginTop: 14,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    paddingHorizontal: 18,
    paddingVertical: 22,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  title: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 22,
    fontFamily: 'ArialRoundedRegular',
  },
  text: {
    marginTop: 10,
    color: COLORS.colorPrimaryIntLetter2,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
    lineHeight: 22,
  },
  gainScreen: {
    flex: 1,
  },
  gainListContent: {
    paddingTop: 2,
    paddingBottom: 120,
  },
  gainCardWrap: {
    marginBottom: 8,
  },
  gainHeaderChip: {
    alignSelf: 'flex-start',
    marginLeft: 14,
    borderRadius: 10,
    backgroundColor: COLORS.colorPrimaryClear2,
    paddingHorizontal: 12,
  },
  gainHeaderChipText: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 19,
    fontFamily: 'OpenSansLight',
  },
  gainCard: {
    marginHorizontal: 14,
    marginTop: 8,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    paddingLeft: 4,
    paddingRight: 4,
    paddingTop: 4,
    paddingBottom: 4,
  },
  gainTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginTop: 8,
  },
  gainTopRowSecondary: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginTop: 8,
  },
  gainFlag: {
    width: 18,
    height: 20,
    resizeMode: 'contain',
    opacity: 0.6,
    marginLeft: 4,
    marginBottom: 3,
    marginRight: 8,
  },
  gainTopHalf: {
    flex: 1,
    marginHorizontal: 4,
  },
  gainTopLabel: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 15,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
  },
  gainValueBox: {
    marginTop: 4,
    height: 33,
    borderRadius: 6,
    backgroundColor: COLORS.backgroundA,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 3,
    paddingBottom: 3,
    paddingLeft: 8,
    paddingRight: 4,
  },
  gainValueBoxText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 18,
    fontFamily: 'OpenSansLight',
  },
  gainTripleValueWrap: {
    flex: 1,
    marginHorizontal: 4,
  },
  gainTripleMiddleWrap: {
    width: 60,
    marginLeft: 8,
    marginRight: 8,
  },
  gainSpreadText: {
    marginTop: 11,
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 18,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'center',
  },
  gainTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 6,
    paddingHorizontal: 6,
  },
  gainTitle: {
    color: COLORS.colorPrimary,
    fontSize: 15,
    fontFamily: 'OpenSansRegular',
  },
  gainVrdWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  gainVrdText: {
    color: COLORS.colorPrimaryClear,
    fontSize: 14,
    fontFamily: 'ArialRoundedRegular',
  },
  gainVrdFlag: {
    width: 15,
    height: 20,
    resizeMode: 'contain',
    opacity: 0.6,
    marginLeft: 3,
  },
  gainDetailCard: {
    borderRadius: 6,
    backgroundColor: COLORS.backgroundA,
    paddingTop: 2,
    paddingBottom: 8,
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 6,
  },
  gainDetailRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    minHeight: 40,
  },
  gainDetailLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 8,
    paddingRight: 8,
  },
  gainDetailIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryIntLetter,
    marginLeft: 0,
    marginRight: 8,
  },
  gainDetailIconSpacer: {
    width: 20,
    marginRight: 8,
  },
  gainDetailText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
  },
  gainExpenseText: {
    color: COLORS.red_clear,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
  },
  gainDetailDotDivider: {
    width: 1,
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 5,
    marginLeft: 4,
    marginRight: 4,
  },
  gainDetailDotDividerDot: {
    width: 1,
    marginTop: 1,
    height: 2,
    borderRadius: 1,
    backgroundColor: COLORS.colorPrimaryIntLetter2,
    opacity: 0.8,
  },
  gainDetailValue: {
    width: 96,
    textAlign: 'right',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
    paddingTop: 10,
    paddingRight: 12,
  },
  gainExpenseValue: {
    width: 96,
    textAlign: 'right',
    color: COLORS.red_clear,
    fontSize: 17,
    fontFamily: 'ArialRoundedRegular',
    paddingTop: 10,
    paddingRight: 12,
  },
  gainTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingTop: 8,
    paddingBottom: 2,
    paddingHorizontal: 12,
  },
  gainTotalLabel: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'OpenSansRegular',
    marginRight: 24,
  },
  gainTotalValue: {
    minWidth: 72,
    textAlign: 'right',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'ArialRoundedRegular',
  },
  gainCompareRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
    marginRight: 12,
    marginBottom: 4,
    paddingHorizontal: 6,
  },
  gainCompareIcon: {
    width: 20,
    height: 18,
    resizeMode: 'contain',
    opacity: 0.5,
    marginRight: 10,
  },
  gainCompareLabel: {
    flex: 1,
    color: COLORS.colorPrimaryClear,
    fontSize: 15,
    fontFamily: 'OpenSansLight',
  },
  gainCompareValue: {
    color: COLORS.colorPrimaryClear,
    fontSize: 16,
    fontFamily: 'ArialRoundedRegular',
  },
  gainSwitchSheet: {
    backgroundColor: 'transparent',
  },
  gainSwitchSheetBody: {
    flex: 1,
    backgroundColor: COLORS.background_bottom_sheet,
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  gainSwitchDock: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingTop: 4,
    paddingLeft: 6,
    paddingRight: 6,
  },
  gainSwitchBtn: {
    width: 77,
    paddingHorizontal: 6,
    paddingTop: 0,
    paddingBottom: 2,
    marginRight: 2,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  gainSwitchIconWrap: {
    width: 40,
    height: 40,
    opacity: 0.6,
  },
  gainSwitchIconWrapActive: {
    opacity: 1,
  },
  gainSwitchIconBg: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryDarkLetter,
  },
  gainSwitchText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: DIMENS.textDetailBottom,
    fontFamily: 'OpenSansLight',
    width: 65,
    paddingTop: 4,
    textAlign: 'center',
    textTransform: 'lowercase',
  },
  gainSwitchTextActive: {
    color: COLORS.colorPrimaryDarkLetter,
  },
  footerLoading: {
    paddingVertical: 20,
  },
  gainBottomSpace: {
    height: 20,
  },
  moneyCardWrap: {
    marginBottom: 8,
  },
  moneyCard: {
    marginHorizontal: 14,
    marginTop: 8,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    paddingLeft: 2,
    paddingRight: 4,
    paddingBottom: 4,
  },
  moneyCardInner: {
    marginTop: 8,
    marginRight: 8,
    backgroundColor: COLORS.white,
  },
  moneySectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    marginLeft: 8,
  },
  moneySectionIconWrap: {
    width: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moneySectionIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryIntLetter,
  },
  moneySectionTitle: {
    width: 70,
    marginLeft: 8,
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
  },
  moneyValuesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  moneyValuesRowLast: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingBottom: 4,
  },
  moneyTotalValuesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 18,
  },
  moneyFlagWrap: {
    width: 30,
    marginLeft: 4,
    marginRight: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moneyFlag: {
    width: 19,
    height: 19,
    resizeMode: 'contain',
    opacity: 0.6,
    marginLeft: 8,
  },
  moneyValuesHalf: {
    flex: 1,
    marginRight: 4,
    marginLeft: 4,
  },
  moneyPlainHalf: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 4,
    marginLeft: 4,
  },
  moneyAmountBox: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 6,
    backgroundColor: COLORS.backgroundA,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 10,
    minHeight: 39,
  },
  moneyPlainAmountWrap: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingTop: 4,
    paddingBottom: 4,
  },
  moneyAmountText: {
    flex: 1,
    textAlign: 'right',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'ArialRoundedRegular',
  },
  moneyArrowWrap: {
    width: 30,
    height: 20,
    marginTop: 3,
    marginBottom: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moneyArrow: {
    width: 19,
    height: 19,
    resizeMode: 'contain',
  },
});

export default styles;
