import { StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';
import { DIMENS } from '../../../core/constants/dimensions';

const styles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  card: {
    width: '100%',
    maxWidth: 500,
    borderRadius: 12,
    backgroundColor: COLORS.background_dialog,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
  },
  typeRow: {
    marginTop: 12,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  typeText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 22,
    fontFamily: 'ArialRoundedRegular',
    textTransform: 'lowercase',
  },
  typeIcon: {
    width: 22,
    height: 22,
    marginLeft: 4,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryDarkLetter,
  },
  fieldsWrap: {
    marginTop: 16,
    marginBottom: 16,
    gap: 12,
  },
  bigRow: {
    height: DIMENS.heightOperationInput,
    borderRadius: 4,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    overflow: 'visible',
  },
  coinSide: {
    width: '40%',
    alignSelf: 'stretch',
    justifyContent: 'center',
    paddingLeft: 2,
  },
  dottedDivider: {
    width: 1,
    alignSelf: 'stretch',
    marginVertical: 6,
    marginHorizontal: 6,
    borderLeftWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#c3bbd6',
  },
  plusText: {
    width: 20,
    textAlign: 'center',
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 28,
    fontFamily: 'ArialRoundedRegular',
  },
  amountInput: {
    flex: 1,
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: DIMENS.bigText,
    fontFamily: 'ArialRoundedRegular',
    paddingLeft: 8,
    paddingRight: 8,
  },
  stateSide: {
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  stateBadge: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stateIcon: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
  },
  fieldRow: {
    height: DIMENS.heightRecCuadInpunt,
    borderRadius: 4,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 8,
  },
  fieldLabel: {
    width: '40%',
    color: COLORS.colorPrimaryIntLetter2,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
  },
  fieldValueWrap: {
    flex: 1,
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  fieldValueText: {
    color: COLORS.word,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
    paddingLeft: 8,
  },
  fieldInput: {
    color: COLORS.word,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
    paddingLeft: 8,
    paddingRight: 8,
    height: DIMENS.heightRecCuadInpunt,
    paddingVertical: 0,
  },
  actionsRow: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cancelBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: DIMENS.heightButton,
  },
  cancelText: {
    color: COLORS.colorDialogButton,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansBold',
  },
  saveBtn: {
    flex: 1,
    minHeight: DIMENS.heightButton,
    borderRadius: 10,
    backgroundColor: COLORS.colorDialogButton,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveText: {
    color: COLORS.white,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
  },
  coinBtn: {
    minHeight: 34,
    justifyContent: 'center',
  },
  coinInline: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  coinFlag: {
    width: 42,
    height: 42,
    resizeMode: 'contain',
    marginRight: 12,
  },
  coinBtnText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: DIMENS.numberItemText,
    fontFamily: 'ArialRoundedRegular',
    textTransform: 'uppercase',
  },
  coinListCard: {
    position: 'absolute',
    top: 56,
    left: 0,
    right: 24,
    maxHeight: 200,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: '#ddd7ea',
    zIndex: 10,
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  coinListScroll: {
    maxHeight: 200,
  },
  coinListRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  coinListFlag: {
    width: 26,
    height: 26,
    resizeMode: 'contain',
    marginRight: 10,
  },
  coinListText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
  },
});

export default styles;
