import { StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';
import { DIMENS } from '../../../core/constants/dimensions';

const styles = StyleSheet.create({
 backdrop: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.45)',
  justifyContent: 'center',
  alignItems: 'center',
  paddingHorizontal: 12,
 },
 card: {
  width: '100%',
  maxWidth: 520,
  borderRadius: 12,
  backgroundColor: COLORS.background_dialog,
  paddingHorizontal: 14,
  paddingTop: 12,
  paddingBottom: 12,
 },
 title: {
  height: 30,
  textAlign: 'center',
  color: COLORS.word,
  fontSize: 20,
  fontFamily: 'OpenSansRegular',
 },
 fieldsWrap: {
  marginTop: 16,
  gap: 12,
 },
 row: {
  height: DIMENS.heightRecCuadInpunt,
  borderRadius: 8,
  backgroundColor: COLORS.white,
  borderWidth: 1,
  borderColor: COLORS.white,
  flexDirection: 'row',
  alignItems: 'center',
  paddingLeft: 8,
 },
 amountRow: {
  height: DIMENS.heightRecCuadInpunt,
  borderRadius: 8,
  backgroundColor: COLORS.white,
  borderWidth: 1,
  borderColor: COLORS.white,
  flexDirection: 'row',
  alignItems: 'center',
  paddingLeft: 8,
 },
 coinSide: {
  width: '42%',
  justifyContent: 'center',
 },
 label: {
  width: '42%',
  color: COLORS.colorPrimaryIntLetter2,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 divider: {
  width: 1,
  alignSelf: 'stretch',
  marginVertical: 2,
  marginHorizontal: 4,
  borderLeftWidth: 1,
  borderStyle: 'dashed',
  borderColor: COLORS.color_line_punt,
 },
 valueSide: {
  flex: 1,
  alignSelf: 'stretch',
  justifyContent: 'center',
 },
 input: {
  color: COLORS.word,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
  paddingLeft: 8,
  paddingRight: 8,
  height: DIMENS.heightRecCuadInpunt,
  paddingVertical: 0,
 },
 dateText: {
  color: COLORS.word,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
  paddingLeft: 8,
 },
 coinTrigger: {
  height: DIMENS.heightRecCuadInpunt,
  justifyContent: 'center',
 },
 coinInline: {
  flexDirection: 'row',
  alignItems: 'center',
 },
 coinFlag: {
  width: 30,
  height: 30,
  margin: 5,
  opacity: 0.9,
  resizeMode: 'contain',
 },
 coinText: {
  color: COLORS.colorPrimaryIntLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'ArialRoundedRegular',
  textTransform: 'uppercase',
  marginLeft: 10,
  marginTop: 5,
  marginBottom: 5,
 },
 amountInput: {
  flex: 1,
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
  paddingLeft: 8,
  paddingRight: 8,
  height: DIMENS.heightRecCuadInpunt,
  paddingVertical: 0,
 },
 actionsRow: {
  marginTop: 20,
  flexDirection: 'row',
  alignItems: 'center',
 },
 cancelBtn: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
  minHeight: DIMENS.heightButton,
 },
 cancelText: {
  color: COLORS.colorDialogButton,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 saveBtn: {
  flex: 1,
  minHeight: DIMENS.heightButton,
  borderRadius: 8,
  backgroundColor: COLORS.colorDialogButton,
  alignItems: 'center',
  justifyContent: 'center',
 },
 saveText: {
  color: COLORS.white,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 coinListCard: {
  position: 'absolute',
  top: DIMENS.heightRecCuadInpunt + 2,
  left: 8,
  right: 6,
  maxHeight: 200,
  borderRadius: 10,
  backgroundColor: COLORS.white,
  borderWidth: 1,
  borderColor: COLORS.colorPrimaryClear2,
  zIndex: 20,
  elevation: 20,
 },
 coinListRow: {
  minHeight: 40,
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: COLORS.white,
  marginLeft: 10,
  paddingLeft: 8,
  paddingRight: 8,
 },
 coinListFlag: {
  width: 30,
  height: 30,
  margin: 5,
  opacity: 0.9,
  resizeMode: 'contain',
 },
 coinListText: {
  color: COLORS.colorPrimaryIntLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'ArialRoundedRegular',
  textTransform: 'uppercase',
  marginLeft: 10,
  marginTop: 5,
  marginBottom: 5,
 },
});

export default styles;
