import { DIMENS } from '../../../core/constants/dimensions';

export const confirmDialogStyles = {
 confirmDialogBackdrop: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.52)',
  justifyContent: 'center',
  alignItems: 'center',
  padding: 6,
 },
 confirmDialogCard: {
  width: '100%',
  maxWidth: 500,
  backgroundColor: '#f3f2f7',
  borderRadius: 12,
  overflow: 'hidden',
  marginTop: DIMENS.dialogMarginTop,
  marginBottom: DIMENS.dialogMarginBottom,
 },
 confirmDialogHeader: {
  paddingTop: 14,
  paddingBottom: 10,
  paddingHorizontal: 16,
  alignItems: 'center',
 },
 confirmDialogType: {
  color: '#4f4677',
  fontSize: DIMENS.titleLargeText,
  fontFamily: 'OpenSansBold',
 },
 confirmDialogBody: {
  paddingHorizontal: 6,
  paddingVertical: 6,
  gap: 8,
 },
 confirmSummaryCard: {
  position: 'relative',
  minHeight: 92,
  borderRadius: 10,
  backgroundColor: '#fcfcfd',
  overflow: 'hidden',
  paddingLeft: 16,
  paddingRight: 16,
  paddingVertical: 8,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  gap: 8,
 },
 confirmSummaryCol: {
  flex: 1,
 },
 confirmSummaryColRight: {
  flex: 1.25,
  alignItems: 'flex-end',
 },
 confirmSummarySubRowLeft: {
  marginTop: 2,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-start',
 },
 confirmSummarySubRowRight: {
  marginTop: 2,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-end',
  width: '100%',
 },
 confirmSummaryStateInline: {
  width: 24,
  height: 24,
  resizeMode: 'contain',
 },
 confirmSummaryMain: {
  color: '#5b5181',
  fontSize: DIMENS.bigText,
  fontFamily: 'OpenSansLight',
 },
 confirmSummaryCode: {
  fontFamily: 'OpenSansLight',
 },
 confirmSummaryNumber: {
  fontFamily: 'OpenSansRegular',
 },
 confirmSummarySub: {
  color: '#8f86aa',
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
 },
 confirmSummarySubLeftText: {
  marginLeft: 8,
  fontFamily: 'OpenSansRegular',
 },
 confirmSummarySubRightText: {
  marginRight: 8,
  fontFamily: 'OpenSansRegular',
  flexShrink: 1,
  minWidth: 0,
  textAlign: 'right',
 },
 confirmSummaryArrowImg: {
  width: 24,
  height: 70,
  resizeMode: 'contain',
  marginHorizontal: 4,
 },
 confirmMetaRow: {
  minHeight: DIMENS.heightButton,
  flexDirection: 'row',
  alignItems: 'center',
  paddingLeft: DIMENS.dialogMarginLeft,
  paddingRight: DIMENS.dialogMarginRight,
 },
 confirmMetaIconCol: {
  width: 34,
  alignItems: 'center',
  justifyContent: 'center',
  marginRight: 8,
 },
 confirmMetaContent: {
  flex: 1,
  justifyContent: 'center',
 },
 confirmMetaIcon: {
  width: 22,
  height: 22,
  resizeMode: 'contain',
 },
 confirmMetaText: {
  color: '#615886',
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
  paddingLeft: 6,
 },
 confirmDialogObsInput: {
  width: '100%',
  minHeight: DIMENS.heightButton,
  borderRadius: 10,
  backgroundColor: '#fdfdfd',
  color: '#615886',
  paddingLeft: 8,
  paddingRight: 12,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
 },
 confirmDialogActions: {
  flexDirection: 'row',
  paddingHorizontal: DIMENS.dialogMarginLeft,
  paddingBottom: DIMENS.dialogMarginBottom,
  paddingTop: 6,
  gap: 10,
  marginTop: 16,
 },
 confirmDialogCancel: {
  flex: 1,
  height: DIMENS.heightButton,
  borderRadius: 10,
  alignItems: 'center',
  justifyContent: 'center',
 },
 confirmDialogCancelText: {
  color: '#6f6392',
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 confirmDialogAccept: {
  flex: 1.2,
  height: DIMENS.heightButton,
  borderRadius: 11,
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#6f6392',
 },
 confirmDialogAcceptText: {
  color: '#ffffff',
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansBold',
 },
 confirmDialogRow: {
  minHeight: 28,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  gap: 10,
 },
 confirmDialogLabel: {
  color: '#7d7397',
  fontSize: DIMENS.captionText,
  fontFamily: 'OpenSansRegular',
 },
 confirmDialogValue: {
  color: '#4f4677',
  fontSize: DIMENS.valueText,
  fontFamily: 'OpenSansRegular',
  flexShrink: 1,
  textAlign: 'right',
 },
} as const;
