import { StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';
import { DIMENS } from '../../../core/constants/dimensions';
import { confirmDialogStyles } from './HomeScreen.confirmDialog.styles';

const styles = StyleSheet.create({

 screen: {
  flex: 1,
  backgroundColor: COLORS.colorPrimaryClear3,
 },
 optionsMenuWrap: {
  position: 'absolute',
  right: 16,
  top: 115,
  zIndex: 25,
  alignItems: 'flex-end',
 },
 optionsButton: {
  width: 40,
  height: 40,
 },
 optionsButtonIcon: {
  width: '100%',
  height: '100%',
  resizeMode: 'contain',
 },
 optionsList: {
  marginTop: 12,
  alignItems: 'flex-end',
 },
 optionsListItem: {
  minHeight: 40,
  borderRadius: 16,
  backgroundColor: COLORS.back_flot,
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 16,
  paddingLeft: 16,
 },
 optionsListItemText: {
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
  paddingRight: 16,
 },
 optionsListItemIcon: {
  width: 40,
  height: 40,
  resizeMode: 'contain',
 },
 scroll: {
  flex: 1,
 },
 scrollContent: {
  paddingHorizontal: 12,
  paddingTop: 4,
  paddingBottom: 180,
 },
 headerRow: {
  height: 48,
  marginTop: 18,
  flexDirection: 'row',
  alignItems: 'center',
 },
 headerHalfLeft: {
  flex: 1,
  flexDirection: 'row',
  justifyContent: 'flex-end',
  alignItems: 'center',
  paddingRight: 14,
 },
 operationType: {
  color: '#64606c',
  fontSize: DIMENS.titleLargeText,
  fontFamily: 'OpenSansRegular',
 },
 arrowDown: {
  color: '#7e7695',
  fontSize: DIMENS.textDetailBottom,
  marginLeft: 8,
 },
 arrowDownIcon: {
  width: 22,
  height: 22,
  marginLeft: 8,
  opacity: 0.7,
 },
 headerHalfRight: {
  flex: 1,
  justifyContent: 'flex-start',
  paddingLeft: 4,
 },
 coinPair: {
  color: COLORS.colorPrimaryClearpp,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 formArea: {
  position: 'relative',
  paddingVertical: 2,
 },
 verticalGuide: {
  position: 'absolute',
  left: '40.8%',
  top: 26,
  bottom: 26,
  width: 1,
  borderLeftWidth: 1,
  borderColor: COLORS.colorPrimaryClearLetter,
  borderStyle: 'dashed',
  marginLeft: 0,
  zIndex: 3,
 },
 cardFrame: {
  position: 'relative',
  marginTop: 12,
  height: 100,
 },
 cardLine: {
  marginHorizontal: 12,
  height: 85,
  borderRadius: 12,
  backgroundColor: COLORS.white,
  flexDirection: 'row',
  alignItems: 'center',
  zIndex: 1,
 },
 cardSectionLeft: {
  flex: 2,
  justifyContent: 'center',
  paddingLeft: 16,
 },
 coinInline: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 10,
 },
 coinFlag: {
  width: 42,
  height: 42,
  resizeMode: 'contain',
 },
 centerGutter: {
  width: 7,
 },
 operatorWrap: {
  width: 22,
  alignItems: 'center',
  justifyContent: 'center',
  marginLeft: 6,
 },
 cardSectionRight: {
  flex: 2,
  justifyContent: 'center',
  paddingRight: 6,
  paddingLeft: 2,
  position: 'relative',
 },
 coinLabel: {
  color: COLORS.colorPrimaryIntLetter,
  fontSize: DIMENS.bigTitleText,
  fontFamily: 'OpenSansRegular',
 },
 operator: {
  width: 18,
  textAlign: 'center',
  color: COLORS.colorPrimaryClearLetter,
  fontSize: DIMENS.operatorText,
  lineHeight: 36,
  fontFamily: 'ArialRoundedRegular',
 },
 inputMock: {
  height: 52,
  borderRadius: 12,
  backgroundColor: 'transparent',
  marginLeft: 2,
  color: COLORS.word,
  fontSize: DIMENS.bigBigText,
  fontFamily: 'ArialRoundedRegular',
 },
 inputMockDisabled: {},
 derivedBadge: {
  position: 'absolute',
  top: 6,
  right: 10,
  color: COLORS.colorPrimaryClearLetter,
  fontSize: 13,
  fontFamily: 'OpenSansRegular',
  opacity: 0.9,
 },
 stateWrap: {
  width: 46,
  marginRight: 8,
  alignItems: 'center',
 },
 statePill: {
  width: 35,
  height: 35,
  alignItems: 'center',
  justifyContent: 'center',
 },
 stateImg: {
  width: 35,
  height: 35,
 },
 affectBubble: {
  position: 'absolute',
  right: 2,
  width: 44,
  height: 44,
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 4,
 },
 affectBubbleIn: {
  bottom: -6,
 },
 affectBubbleOut: {
  bottom: -2,
 },
 affectBubbleImg: {
  width: 30,
  height: 30,
  resizeMode: 'contain',
 },
 middleRowWrap: {
  height: 40,
 },
 middleRow: {
  flex: 1,
  marginRight: 68,
  flexDirection: 'row',
  alignItems: 'center',
  zIndex: 1,
 },
 middleLeft: {
  flex: 2,
  alignItems: 'flex-end',
  paddingRight: 4,
 },
 middleRight: {
  flex: 2,
  flexDirection: 'row',
  alignItems: 'center',
  paddingLeft: 0,
  position: 'relative',
 },
 midArrowImg: {
  width: 22,
  height: 40,
  marginRight: 10,
  tintColor: COLORS.colorPrimaryDarkLetter,
  resizeMode: 'contain',
 },
 exchangeInputMock: {
  flex: 1,
  height: DIMENS.heightButton,
  borderRadius: 10,
  backgroundColor: COLORS.white,
  paddingHorizontal: 10,
  color: COLORS.word,
  fontSize: DIMENS.bigTitleText,
  fontFamily: 'AriaRounded',
 },
 cleanRateRow: {
  marginTop: 12,
  marginHorizontal: 12,
  height: DIMENS.heightButton,
  flexDirection: 'row',
  alignItems: 'center',
 },
 cleanSide: {
  width: '50%',
  paddingLeft: 72,
 },
 cleanButton: {
  width: 36,
  height: 36,
  alignItems: 'center',
  justifyContent: 'center',
 },
 cleanIcon: {
  color: '#c1bccf',
  fontSize: DIMENS.bigBigText,
 },
 cleanImg: {
  width: 33,
  height: 33,
  opacity: 0.45,
  resizeMode: 'contain',
 },
 rateSide: {
  width: '50%',
  justifyContent: 'center',
  alignItems: 'flex-start',
 },
 rateTextRow: {
  width: '100%',
  flexDirection: 'row',
  justifyContent: 'flex-start',
  alignItems: 'center',
 },
 rateText: {
  color: COLORS.colorPrimaryClearpp,
  fontSize: DIMENS.generalText,
  textAlign: 'left',
  fontFamily: 'OpenSansRegular',
 },
 rateValueText: {
  minWidth: 24,
  color: COLORS.colorPrimaryClearpp,
  fontSize: DIMENS.generalText,
  textAlign: 'left',
  fontFamily: 'OpenSansRegular',
 },
 confirmRow: {
  marginTop: 12,
  marginHorizontal: 12,
  height: 45,
  flexDirection: 'row',
  alignItems: 'stretch',
 },
 clientGhost: {
  flex: 1,
  justifyContent: 'center',
  zIndex: 3,
 },
 clientGhostSelected: {
  zIndex: 4,
 },
 clientBox: {
  flex: 1,
  borderRadius: 10,
  backgroundColor: 'transparent',
  justifyContent: 'center',
  paddingHorizontal: 12,
  position: 'relative',
  overflow: 'hidden',
 },
 clientBoxSelected: {
  backgroundColor: COLORS.white,
  marginRight: -12,
 },
 clientGhostText: {
  color: COLORS.colorPrimaryIntLetter2,
  fontSize: DIMENS.bigText,
  fontFamily: 'ArialRoundedRegular',
  textAlign: 'center',
 },
 clearClientBtn: {
  position: 'absolute',
  top: 2,
  left: 4,
  width: 24,
  height: 24,
  zIndex: 5,
  alignItems: 'center',
  justifyContent: 'center',
 },
 clearClientText: {
  color: COLORS.word_clear,
  fontSize: DIMENS.captionText,
  fontFamily: 'OpenSansRegular',
 },
 confirmBtn: {
  flex: 1,
  backgroundColor: COLORS.colorPrimaryChange,
  borderRadius: 12,
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1,
 },
 confirmText: {
  color: COLORS.white,
  fontSize: DIMENS.bigText,
  fontFamily: 'OpenSansRegular',
 },
 fabColumn: {
  position: 'absolute',
  right: 30,
  bottom: 50,
  gap: 16,
  zIndex: 6,
 },
 fab: {
  width: 50,
  height: 50,
  alignItems: 'center',
  justifyContent: 'center',
 },
 fabImg: {
  width: 50,
  height: 50,
 },
 devBaseUrlWrap: {
  position: 'absolute',
  left: 12,
  bottom: 98,
  maxWidth: '72%',
  zIndex: 7,
 },
 devBaseUrlText: {
  color: '#9A9AA3',
  fontSize: 10,
  fontFamily: 'OpenSansRegular',
  textAlign: 'left',
 },
 ...confirmDialogStyles,
 coinPickerBackdrop: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.08)',
 },
 coinPickerCard: {
  position: 'absolute',
  left: 20,
  width: 196,
  maxHeight: 430,
  backgroundColor: COLORS.backgroundA,
  borderRadius: 22,
  paddingVertical: 8,
  shadowColor: '#000',
  shadowOpacity: 0.16,
  shadowRadius: 18,
  elevation: 10,
 },
 coinPickerCardIn: {
  top: 270,
 },
 coinPickerCardOut: {
  top: 405,
 },
 coinPickerRow: {
  height: 50,
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 12,
  gap: 10,
 },
 coinPickerFlag: {
  width: 32,
  height: 32,
  resizeMode: 'contain',
 },
 coinPickerText: {
  color: COLORS.colorPrimaryIntLetter,
  fontSize: DIMENS.bigText,
  lineHeight: 24,
  fontFamily: 'ArialRoundedRegular',
 },
 coinPickerEmpty: {
  minHeight: 150,
  alignItems: 'center',
  justifyContent: 'center',
  paddingHorizontal: 12,
  gap: 8,
 },
 coinPickerEmptyText: {
  color: COLORS.word_clear,
  fontSize: DIMENS.textDetailBottom,
  textAlign: 'center',
  fontFamily: 'OpenSansRegular',
 },
 coinPickerErrorDetail: {
  color: COLORS.red_clear,
  fontSize: DIMENS.tinyText,
  textAlign: 'center',
  fontFamily: 'OpenSansRegular',
 },
 coinPickerRetryBtn: {
  marginTop: 4,
  backgroundColor: COLORS.colorPrimaryChange,
  borderRadius: 10,
  paddingHorizontal: 12,
  paddingVertical: 6,
 },
 coinPickerRetryText: {
  color: COLORS.white,
  fontSize: DIMENS.captionText,
  fontFamily: 'OpenSansRegular',
 },
 sheet: {
  position: 'absolute',
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'transparent',
 },
 sheetBody: {
  flex: 1,
  backgroundColor: COLORS.background_bottom_sheet,
  borderRadius: 8,
  overflow: 'hidden',
 },
 sheetListContent: {
  paddingHorizontal: 4,
  paddingTop: 6,
  paddingBottom: 14,
 },
 center: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  padding: 24,
 },
 errorTitle: {
  fontSize: DIMENS.textDetailBottom,
  fontFamily: 'OpenSansBold',
  marginBottom: 8,
  textAlign: 'center',
  color: COLORS.colorPrimaryDarkLetter,
 },
 errorText: {
  color: COLORS.word_clear,
  textAlign: 'center',
  marginBottom: 16,
  fontFamily: 'OpenSansRegular',
 },
 retryButton: {
  backgroundColor: COLORS.colorPrimaryChange,
  paddingHorizontal: 14,
  paddingVertical: 10,
  borderRadius: 8,
 },
 retryText: {
  color: COLORS.white,
  fontFamily: 'OpenSansBold',
 },
 viewAllButton: {
  alignSelf: 'center',
  marginTop: 12,
  marginBottom: 16,
  paddingHorizontal: 18,
  paddingVertical: 10,
  borderRadius: 16,
  backgroundColor: COLORS.back_flot,
 },
 viewAllButtonText: {
  color: COLORS.colorPrimaryDarkLetter,
  fontFamily: 'OpenSansRegular',
  fontSize: DIMENS.generalText,
  textTransform: 'lowercase',
 },
 emptyWrap: {
  marginTop: 18,
  alignItems: 'center',
  gap: 8,
 },
 emptyText: {
  color: COLORS.word_clear,
  fontFamily: 'OpenSansRegular',
 },
 affectConfirmBackdrop: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.52)',
  justifyContent: 'center',
  alignItems: 'center',
  padding: 10,
 },
 affectConfirmCard: {
  width: '100%',
  maxWidth: 500,
  borderRadius: 12,
  backgroundColor: COLORS.background_dialog,
  paddingHorizontal: DIMENS.dialogMarginLeft,
  paddingTop: DIMENS.dialogMarginTop,
  paddingBottom: DIMENS.dialogMarginBottom,
 },
 affectConfirmTitle: {
  height: 36,
  textAlign: 'center',
  color: COLORS.word,
  fontSize: 20,
  fontFamily: 'OpenSansRegular',
 },
 affectConfirmText: {
  marginTop: 12,
  color: COLORS.word,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
  lineHeight: 24,
 },
 affectConfirmTextStrong: {
  fontFamily: 'OpenSansBold',
 },
 affectConfirmActions: {
  marginTop: 20,
  flexDirection: 'row',
  alignItems: 'center',
  gap: 10,
 },
 affectConfirmCancelBtn: {
  flex: 1,
  minHeight: DIMENS.heightButton,
  justifyContent: 'center',
  alignItems: 'center',
 },
 affectConfirmCancelText: {
  color: COLORS.colorDialogButton,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 affectConfirmOkBtn: {
  flex: 1,
  minHeight: DIMENS.heightButton,
  borderRadius: 8,
  backgroundColor: COLORS.colorDialogButton,
  justifyContent: 'center',
  alignItems: 'center',
 },
 affectConfirmOkText: {
  color: COLORS.white,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansBold',
 },
});

export default styles;
