export const DIMENS = {
 tinyText: 12,
 captionText: 14,
 valueText: 15,
 titleText: 20,
 titleLargeText: 22,
 bigTitleText: 24,
 operatorText: 33,
 bigBigText: 28,
 bigText: 20,
 bigTextNumbers: 27,
 numberItemText: 19,
 generalText: 18,
 smallText: 17,
 textDetailBottom: 16,
 itemOpByCoinTypeText: 19,
 itemOpByCoinAmountText: 21,
 itemOpByCoinMetaText: 17,
 heightButton: 35,
 dialogMarginTop: 11,
 dialogMarginLeft: 24,
 dialogMarginRight: 24,
 dialogMarginBottom: 11,
};
