import { StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';
import { DIMENS } from '../../../core/constants/dimensions';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#dfe0e5',
  },
  content: {
    flex: 1,
  },
  tabsRow: {
    height: 58,
    flexDirection: 'row',
    backgroundColor: COLORS.colorPrimaryDarkChange,
  },
  tabBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
    paddingHorizontal: 8,
  },
  tabBtnActive: {
    borderBottomColor: COLORS.white,
  },
  tabText: {
    color: '#8f9088',
    fontSize: DIMENS.numberItemText,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
    textTransform: 'lowercase',
  },
  tabTextActive: {
    color: COLORS.white,
  },
  listContent: {
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 28,
  },
  sectionHeaderWrap: {
    paddingTop: 2,
    paddingBottom: 2,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  sectionHeaderChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    minHeight: 0,
    borderRadius: 10,
    backgroundColor: COLORS.colorPrimaryClear2,
    paddingHorizontal: 12,
    paddingVertical: 2,
    justifyContent: 'center',
    marginLeft: 2,
  },
  sectionHeaderText: {
    color: COLORS.colorPrimaryIntLetter,
    fontSize: 18,
    fontFamily: 'OpenSansLight',
  },
  sectionHeaderWeekdayText: {
    color: COLORS.colorPrimaryDark,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
  },
  sectionHeaderDayText: {
    color: COLORS.colorPrimaryDark,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
    paddingLeft: 6,
  },
  sectionHeaderMonthText: {
    color: COLORS.colorPrimaryDark,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
    paddingLeft: 6,
  },
  sectionHeaderYearText: {
    color: COLORS.colorPrimaryDark,
    fontSize: 18,
    fontFamily: 'OpenSansRegular',
    paddingLeft: 6,
  },
  checkCard: {
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingTop: 12,
    paddingBottom: 12,
    marginTop: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
    overflow: 'visible',
  },
  checkCardPending: {
    backgroundColor: '#FCE8BF',
  },
  checkCardApproved: {
    backgroundColor: COLORS.white,
  },
  checkPendingBadge: {
    position: 'absolute',
    top: -14,
    left: 18,
    width: 30,
    height: 30,
    resizeMode: 'contain',
    zIndex: 3,
  },
  checkDoneBadge: {
    position: 'absolute',
    top: -25,
    width: 34,
    height: 34,
    resizeMode: 'contain',
    zIndex: -4,
  },
  checkTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
    marginRight: 12,
  },
  checkMainRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginLeft: 8,
    marginRight: 12,
    marginTop: 4,
  },
  checkFooterRowLayout: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginTop: 10,
    marginLeft: 14,
    marginRight: 18,
    minHeight: 40,
  },
  checkDetailRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginLeft: 14,
    marginRight: 18,
    paddingBottom: 2,

  },
  checkLeftColumn: {
    flex: 1.28,
    minWidth: 0,
  },
  checkMiddleColumn: { // esta es la linea punteada del medio
    width: 10,
    alignItems: 'center',
    alignSelf: 'stretch',
    marginLeft: 16,
    marginRight: 12,
  },
  checkDotDivider: {
    width: 1,
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 0,
  },
  checkDotDividerDot: {
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: COLORS.colorPrimaryClearLetter,
    opacity: 0.8,
  },
  checkRightColumn: {
    flex: 0.92,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  checkCardTop: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginLeft: 8,
    marginRight: 12,
  },
  checkCardLeft: {
    flex: 1.28,
    justifyContent: 'space-between',
    paddingRight: 2,
  },
  checkCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 4,
    paddingRight: 0,
  },
  checkLeadIcon: {
    width: 35,
    height: 35,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryClearLetter,
    marginLeft: 2,
    marginRight: 8,
  },
  checkCenterBadge: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
    marginTop: -22,
    marginBottom: 2,
  },
  checkCardPartyLabel: {
    color: COLORS.colorPrimaryIntLetter2,
    fontSize: DIMENS.textDetailBottom,
    fontFamily: 'OpenSansRegular',
  },
  checkCardPartyValue: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 18,
    marginTop: 12,
    fontFamily: 'ArialRoundedRegular',
    flexShrink: 1,
  },
  checkCardDividerWrap: {
    width: 38,
    alignItems: 'center',
    justifyContent: 'flex-start',
    alignSelf: 'stretch',
    paddingTop: 12,
    marginLeft: 18,
    marginRight: 8,
  },
  checkMainGuide: {
    minHeight: 80,
    marginTop: 8,
  },
  checkFooterGuide: {
    minHeight: 50,
  },
  checkCardRight: {
    flex: 0.92,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },
  checkHeaderIcon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryClearLetter,
    marginBottom: 2,
  },
  checkHeaderSpacer: {
    width: 40,
    height: 40,
    marginBottom: 2,
  },
  checkCardAmountLabel: {
    color: COLORS.colorPrimaryIntLetter2,
    fontSize: 18,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'center',
    width: '100%',
    paddingTop: 8,
  },
  checkCardAmountValue: {
    marginTop: 34,
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 22,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'center',
  },
  checkFooterRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginTop: 10,
    marginLeft: 14,
    marginRight: 18,
    minHeight: 40,
  },
  checkFooterLeft: {
    flex: 1.28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 2,
  },
  checkFooterLeftRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 2,
  },
  checkFooterDate: {
    width: 72,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 17,
    fontFamily: 'OpenSansRegular',
  },
  checkFooterState: {
    flex: 1,
    textAlign: 'center',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
  },
  checkFooterDividerWrap: {
    width: 38,
    alignItems: 'center',
    alignSelf: 'stretch',
    justifyContent: 'center',
    marginLeft: 19,
    marginRight: 8,
    minHeight: 52,
  },
  checkFooterAmountWrap: {
    flex: 0.92,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    minHeight: 40,
  },
  checkFooterAmountButton: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    minHeight: 40,
  },
  checkFooterAmount: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    marginTop: 10,
    fontFamily: 'ArialRoundedRegular',
  },
  checkFooterMiniArrow: {  //downup
    width: 25,
    height: 30,
    marginLeft: 4,
    marginBottom: 4,
    marginTop: 10,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryDark,
    opacity: 0.9,
  },
  checkArrowWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 46,
    paddingBottom: 0,
  },
  checkArrowIcon: {
    width: 35,
    height: 18,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryClearLetter,
    opacity: 0.5,
  },
  checkArrowIconExpandedSpacing: {
    marginTop: 6,
  },
  checkExpanded: {
    paddingTop: 0,
    paddingLeft: 14,
    paddingBottom: 0,
  },
  checkInfoExpanded: {
    paddingLeft: 12,
    paddingRight: 12,
    paddingTop: 10,
  },
  checkInfoExpandedApproved: {
    paddingTop: 8,
    paddingLeft: 12,
    paddingRight: 12,
    paddingBottom: 4,
  },
  checkExpandedDivider: {
    height: 1,
    backgroundColor: COLORS.shadownav,
    opacity: 0.2,
    marginBottom: 14,
  },
  checkPendingExpandedGrid: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingTop: 0,
    paddingBottom: 2,
    marginTop: -8,
  },
  checkPendingExpandedLeftColumn: {
    flex: 1.28,
    justifyContent: 'space-between',
    paddingRight: 26,
    gap: 10,
  },
  checkPendingExpandedLabel: {
    textAlign: 'right',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
    minHeight: 28,
  },
  checkPendingExpandedDividerWrap: {
    width: 38,
    alignItems: 'center',
    alignSelf: 'stretch',
    justifyContent: 'flex-start',
    marginLeft: 19,
    marginRight: 8,
    // minHeight: 132,
  },
  checkPendingExpandedRightColumn: {
    flex: 0.92,
    justifyContent: 'space-between',
    gap: 10,
  },
  checkPendingExpandedValue: {
    textAlign: 'right',
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
    marginRight: 8,
    minHeight: 28,
  },
  checkPendingAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    marginLeft: 14,
    marginRight: 18,
  },
  checkPendingAmountLabel: {
    color: COLORS.colorPrimaryIntLetter2,
    fontSize: 16,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'right',
    paddingRight: 18,
  },
  checkPendingAmountGuideSpacer: {
    width: 1,
    minHeight: 20,
    opacity: 0,
  },
  checkPendingAmountValue: {
    width: '100%',
    color: COLORS.colorPrimaryIntLetter2,
    fontSize: 19,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'right',
    marginRight: 18,
  },
  checkPendingButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 14,
    marginLeft: 14,
    marginRight: 18,
  },
  checkPendingLoadedAmountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: 34,
    marginRight: 22,
  },
  checkPendingLoadedAmountLabel: {
    color: COLORS.colorPrimaryIntLetter2,
    fontSize: 16,
    marginLeft: -12,
    fontFamily: 'OpenSansRegular',
  },
  checkPendingLoadedAmountValue: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 18,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'right',
  },
  checkPendingLoadsWrap: {
    marginTop: 4,
    marginLeft: 14,
    marginRight: 18,
    gap: 8,
  },
  checkApprovedLoadsWrap: {
    marginLeft: 14,
    marginRight: 18,
    gap: 8,
  },
  checkApprovedEmptyWrap: {
    paddingTop: 8,
    paddingBottom: 6,
  },
  checkApprovedEmptyText: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 17,
    fontFamily: 'OpenSansLight',
    textAlign: 'center',
  },
  checkPendingBottomRowWithLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginLeft: -90,
  },
  checkPendingBottomRowArrowOnly: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginLeft: 44,
  },
  checkPendingBottomLabel: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 17,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'center',
  },
  checkPendingArrowBtn: {
    marginLeft: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkPendingArrowBtnSolo: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkPendingActionWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkPendingActionSpacer: {
    flex: 1,
  },
  checkPendingActionWideWrap: {
    flex: 1,
    marginLeft: 10,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  checkPendingActionBtn: {
    width: 140,
    minHeight: 30,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryClear2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  checkPendingActionWideBtn: {
    width: 146,
    minHeight: 28,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryClear2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkPendingActionText: {
    color: COLORS.word,
    fontSize: 16,
    fontFamily: 'OpenSansRegular',
  },
  checkMoreInfoRow: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',

  },
  checkMoreInfoRowApproved: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  checkMoreInfoRowPending: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginLeft: 'auto',
  },
  checkMoreInfoIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryClearLetter,

  },
  checkMoreInfoText: {
    color: COLORS.colorPrimaryIntLetter2,
    fontSize: 19,
    fontFamily: 'OpenSansRegular',
  },
  checkPendingInfoActionsRow: {
    marginTop: 8,
    marginLeft: 14,
    marginRight: 8,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checkPendingRejectBtn: {
    minHeight: 30,
    borderRadius: 8,
    backgroundColor: COLORS.colorPrimaryClear2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  checkPendingRejectBtnText: {
    color: COLORS.word,
    fontSize: 15,
    fontFamily: 'OpenSansRegular',
  },
  checkInfoDetails: {
    gap: 8,
  },
  checkInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checkInfoLabel: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 16,
    fontFamily: 'OpenSansRegular',
    paddingRight: 14,
  },
  checkInfoValue: {
    flex: 1,
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 16,
    fontFamily: 'OpenSansLight',
    textAlign: 'right',
  },
  checkExpandedText: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: 17,
    lineHeight: 26,
    fontFamily: 'ArialRoundedRegular',
  },
  checkRatesWrap: {
    marginTop: 11,
    gap: 12,
    paddingTop: 8,
    paddingLeft: 36,
    paddingRight: 0,
  },
  checkRateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  checkRateIcon: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
    marginRight: 18,
  },
  checkRateBadge: {
    minWidth: 110,
    height: 28,
    borderRadius: 4,
    backgroundColor: COLORS.background_dialog,
    paddingLeft: 10,
    paddingRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkRateValue: {
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 19,
    fontFamily: 'ArialRoundedRegular',
    textAlign: 'center',
  },
  checkRatePercent: {
    marginLeft: 6,
    color: COLORS.colorPrimaryClearLetter,
    fontSize: 19,
    fontFamily: 'OpenSansLight',
    marginRight: 6,
  },
  checkRateSwap: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
    tintColor: COLORS.colorPrimaryClearLetter,
    opacity: 0.42,
    marginLeft: 8,
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 48,
    gap: 10,
  },
  emptyText: {
    color: COLORS.word_clear,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
  },
  retryBtn: {
    marginTop: 8,
    minHeight: 40,
    borderRadius: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.colorPrimaryChange,
  },
  retryText: {
    color: COLORS.white,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
  },
  placeholderWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  placeholderTitle: {
    color: COLORS.colorPrimaryDarkLetter,
    fontSize: DIMENS.bigText,
    fontFamily: 'OpenSansBold',
  },
  placeholderText: {
    marginTop: 10,
    color: COLORS.word_clear,
    fontSize: DIMENS.generalText,
    fontFamily: 'OpenSansRegular',
    textAlign: 'center',
  },
  footerLoading: {
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
