import { Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../../core/constants/colors';
import { DIMENS } from '../../../core/constants/dimensions';
import accountStyles from '../../accounts/screens/InformationByAccountScreen.styles';

const isWeb = Platform.OS === 'web';

const styles = StyleSheet.create({
 ...accountStyles,
 tabsRow: {
  ...accountStyles.tabsRow,
  minHeight: isWeb ? 48 : 58,
 },
 placeholderWrap: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
  paddingHorizontal: 24,
 },
 placeholderTitle: {
  color: COLORS.word,
  fontSize: 24,
  fontFamily: 'OpenSansRegular',
  textAlign: 'center',
 },
 placeholderText: {
  marginTop: 10,
  color: COLORS.word_clear,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
  textAlign: 'center',
 },
 summaryText: {
  ...accountStyles.summaryText,
  paddingHorizontal: 20,
  paddingTop: 24,
 },
 summaryWrap: {
  ...accountStyles.summaryWrap,
  paddingTop: 0,
 },
 summaryContent: {
  ...accountStyles.summaryContent,
  paddingBottom: 220,
 },
 summaryFab: {
  ...accountStyles.summaryFab,
  bottom: 108,
 },
 pendingRow: {
  flexDirection: 'row',
  justifyContent: 'flex-end',
  alignItems: 'center',
  marginTop: -12,
  marginRight: 46,
  marginBottom: 10,
 },
 pendingRowText: {
  color: COLORS.colorPrimaryClearLetter,
  fontSize: 18,
  fontFamily: 'ArialRoundedRegular',
  marginRight: 8,
 },
 pendingRowIcon: {
  width: 20,
  height: 20,
  opacity: 0.5,
  resizeMode: 'contain',
 },
 expandedContentWrap: {
  paddingBottom: 14,
 },
 summaryGeneralWrap: {
  backgroundColor: COLORS.background_selected,
 },
 userFilterCaption: {
  paddingHorizontal: 16,
  paddingTop: 10,
  paddingBottom: 6,
  color: COLORS.word_clear,
  fontSize: 12,
  fontFamily: 'OpenSansRegular',
 },
 viewOptionsWrap: {
  position: 'absolute',
  top: 12,
  right: 12,
  zIndex: 20,
  alignItems: 'flex-end',
 },
 viewOptionsButton: {
  width: 36,
  height: 36,
 },
 viewOptionsButtonBg: {
  width: '100%',
  height: '100%',
  resizeMode: 'contain',
 },
 viewOptionsList: {
  marginTop: 16,
  alignItems: 'flex-end',
 },
 viewOptionsCard: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: COLORS.back_flot,
  borderRadius: 16,
  paddingLeft: 16,
  paddingRight: 8,
  paddingVertical: 6,
  marginBottom: 12,
 },
 viewOptionsTextWrap: {
  marginRight: 8,
 },
 viewOptionsTitle: {
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 viewOptionsSubtitle: {
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: 16,
  fontFamily: 'OpenSansRegular',
 },
 viewOptionsIcon: {
  width: 40,
  height: 40,
  resizeMode: 'contain',
 },
 summaryInnerList: {
  paddingHorizontal: 10,
  paddingBottom: 10,
 },
 summaryInnerCard: {
  marginBottom: 10,
  paddingHorizontal: 16,
  paddingVertical: 14,
  backgroundColor: COLORS.background_selected,
  borderRadius: 12,
 },
 summaryInnerRow: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
 },
 summaryInnerDivider: {
  height: 1,
  marginVertical: 8,
  backgroundColor: COLORS.color_line_div,
  opacity: 0.7,
 },
 summaryInnerLabel: {
  flex: 1,
  color: COLORS.word,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 summaryInnerValue: {
  flex: 1,
  textAlign: 'right',
  color: COLORS.word,
  fontSize: DIMENS.bigText ?? 24,
  fontFamily: 'OpenSansRegular',
 },
 balanceCoinsBlock: {
  paddingTop: 6,
  paddingHorizontal: 12,
  backgroundColor: COLORS.background,
 },
 balanceCoinsBlockExpanded: {
  backgroundColor: COLORS.background_selected,
 },
 balanceCoinsTopRow: {
  minHeight: 60,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  paddingBottom: 6,
  backgroundColor: COLORS.background,
 },
 balanceCoinsTopRowExpanded: {
  backgroundColor: COLORS.background_selected,
 },
 balanceCoinsTopLeft: {
  flex: 1,
  flexDirection: 'row',
  alignItems: 'center',
  paddingLeft: 10,
 },
 balanceCoinsFlag: {
  width: 40,
  height: 40,
  opacity: 0.8,
  resizeMode: 'contain',
 },
 balanceCoinsCode: {
  marginLeft: 10,
  width: 80,
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
  textTransform: 'uppercase',
 },
 balanceCoinsAmount: {
  flex: 1,
  textAlign: 'right',
  marginRight: 46,
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: 22,
  fontFamily: 'ArialRoundedRegular',
 },
 balanceCoinsExpandedWrap: {
  paddingLeft: 14,
  paddingRight: 24,
  paddingBottom: 18,
 },
 balanceCoinsSaldoRow: {
  minHeight: 50,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginRight: 10,
 },
 balanceCoinsSaldoLabel: {
  color: COLORS.word,
  fontSize: 19,
  fontFamily: 'OpenSansRegular',
 },
 balanceCoinsSaldoValue: {
  color: COLORS.word,
  fontSize: 19,
  fontFamily: 'ArialRoundedRegular',
 },
 balanceCoinDayWrap: {
  paddingBottom: 8,
 },
 balanceCoinToggleRow: {
  minHeight: 44,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginRight: 10,
 },
 balanceCoinLabelSide: {
  flex: 1,
  flexDirection: 'row',
  alignItems: 'center',
 },
 balanceCoinArrow: {
  width: 18,
  height: 18,
  marginRight: 6,
  opacity: 0.7,
  resizeMode: 'contain',
  transform: [{ rotate: '-90deg' }],
 },
 balanceCoinArrowOpen: {
  transform: [{ rotate: '0deg' }],
 },
 balanceCoinLabel: {
  color: COLORS.word,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
 },
 balanceCoinValue: {
  minWidth: 80,
  textAlign: 'right',
  color: COLORS.word,
  fontSize: DIMENS.bigText,
  fontFamily: 'OpenSansRegular',
 },
 balanceCoinLine: {
  height: 1,
  backgroundColor: COLORS.color_line_div,
  opacity: 0.55,
 },
 balanceCoinDetailGroup: {
  paddingLeft: 40,
  paddingTop: 2,
  paddingBottom: 4,
  gap: 8,
 },
 balanceCoinSubRow: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginRight: 10,
 },
 balanceCoinSubLabel: {
  flex: 1,
  color: COLORS.colorPrimaryIntLetter2,
  fontSize: 17,
  fontFamily: 'OpenSansLight',
 },
 balanceCoinSubValue: {
  minWidth: 90,
  textAlign: 'right',
  color: COLORS.colorPrimaryIntLetter2,
  fontSize: 17,
  fontFamily: 'OpenSansLight',
 },
 balanceCoinPlainRow: {
  minHeight: 44,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  paddingLeft: 24,
  marginRight: 10,
 },
 balanceCoinPlainLabel: {
  flex: 1,
  color: COLORS.word,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
 },
 balanceCoinPlainValue: {
  minWidth: 80,
  textAlign: 'right',
  color: COLORS.word,
  fontSize: DIMENS.bigText,
  fontFamily: 'OpenSansRegular',
 },
 balanceCoinsLoadMoreIcon: {
  width: 30,
  height: 30,
  resizeMode: 'contain',
  tintColor: COLORS.colorPrimaryClearLetter,
  opacity: 0.8,
 },
 balanceListContent: {
  paddingTop: 0,
  paddingBottom: 120,
 },
 balanceFooterWrap: {
  minHeight: 56,
  alignItems: 'center',
  justifyContent: 'center',
  paddingBottom: 18,
 },
 balanceFooterText: {
  marginTop: 8,
  color: COLORS.word_clear,
  fontSize: 14,
  fontFamily: 'OpenSansRegular',
  textAlign: 'center',
 },
 balanceFooterHint: {
  color: COLORS.colorPrimaryClearLetter,
  fontSize: 13,
  fontFamily: 'OpenSansRegular',
  textAlign: 'center',
 },
 balanceItemWrap: {
  backgroundColor: COLORS.background,
  paddingLeft: 12,
  paddingRight: 12,
 },
 balanceItemAssignable: {
  backgroundColor: COLORS.green2,
 },
 balanceItemExpanded: {
  backgroundColor: COLORS.background_selected,
 },
 balanceHeaderRow: {
  flexDirection: 'row',
  alignItems: 'flex-start',
  paddingTop: 12,
  paddingBottom: 12,
 },
 balanceHeaderLeft: {
  flex: 1,
  flexDirection: 'row',
  alignItems: 'flex-start',
 },
 balanceDateBlock: {
  minWidth: 112,
 },
 balanceDateLine: {
  flexDirection: 'row',
  alignItems: 'center',
 },
 balanceMonthText: {
  color: COLORS.colorPrimaryIntLetter,
  fontSize: 16,
  fontFamily: 'OpenSansRegular',
 },
 balanceDayNameText: {
  color: COLORS.colorPrimaryDark,
  fontSize: 16,
  fontFamily: 'OpenSansLight',
 },
 balanceDateNumberText: {
  marginLeft: 4,
  color: COLORS.colorPrimaryIntLetter,
  fontSize: 13,
  fontFamily: 'OpenSansLight',
 },
 balanceYearText: {
  marginTop: 2,
  color: COLORS.colorPrimaryIntLetter,
  fontSize: 12,
  fontFamily: 'OpenSansLight',
 },
 balanceDateText: {
  color: COLORS.colorPrimaryClearLetter,
  fontSize: 12,
  fontFamily: 'OpenSansLight',
 },
 balanceCurrencyLabel: {
  marginLeft: 34,
  color: COLORS.colorPrimaryIntLetter,
  fontSize: 16,
  fontFamily: 'OpenSansLight',
 },
 balanceGainText: {
  flex: 1.3,
  textAlign: 'right',
  color: COLORS.colorPrimaryIntLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 balanceAssignMarkWrap: {
  marginLeft: 12,
  minWidth: 28,
  alignItems: 'center',
 },
 balanceAssignedGreen: {
  width: 28,
  height: 28,
  position: 'relative',
  alignItems: 'center',
  justifyContent: 'center',
 },
 balanceAssignedGreenBase: {
  position: 'absolute',
  width: 28,
  height: 28,
  tintColor: COLORS.green_selected,
  resizeMode: 'contain',
 },
 balanceAssignedGreenIcon: {
  width: 18,
  height: 18,
  resizeMode: 'contain',
 },
 balanceAssignedIcon: {
  width: 28,
  height: 28,
  opacity: 0.6,
  resizeMode: 'contain',
 },
 balanceExpandedOptions: {
  flexDirection: 'row',
  marginTop: 8,
  marginBottom: 10,
 },
 balanceOptionCol: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'flex-start',
 },
 balanceOptionIcon: {
  width: 30,
  height: 30,
  opacity: 0.5,
  resizeMode: 'contain',
 },
 balanceOptionLine: {
  alignSelf: 'stretch',
  height: 1,
  marginTop: 8,
  marginLeft: 8,
  marginRight: 8,
  marginBottom: 2,
  backgroundColor: COLORS.color_line_div,
  opacity: 0.55,
 },
 balanceOptionText: {
  color: COLORS.colorPrimaryIntLetter2,
  fontSize: 15,
  fontFamily: 'OpenSansLight',
  textAlign: 'center',
 },
 balanceOptionTextCenter: {
  color: COLORS.colorPrimaryIntLetter2,
  fontSize: 15,
  fontFamily: 'OpenSansLight',
  textAlign: 'center',
 },
 balanceDollarizedList: {
  marginTop: 8,
  marginBottom: 8,
  paddingTop: 6,
 },
 balanceDollarizedRow: {
  minHeight: 36,
  flexDirection: 'row',
  alignItems: 'center',
  marginRight: 8,
  paddingBottom: 8,
  marginBottom: 4,
 },
 balanceDollarizedCoinSide: {
  flex: 1,
  flexDirection: 'row',
  alignItems: 'center',
  paddingLeft: 12,
 },
 balanceDollarizedFlag: {
  width: 35,
  height: 30,
  resizeMode: 'contain',
  opacity: 0.9,
 },
 balanceDollarizedCode: {
  marginLeft: 4,
  color: COLORS.colorPrimaryClearLetter,
  fontSize: 16,
  fontFamily: 'ArialRoundedRegular',
  textTransform: 'uppercase',
 },
 balanceDollarizedAmount: {
  minWidth: 92,
  textAlign: 'right',
  marginRight: 16,
  color: COLORS.colorPrimaryClearLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'ArialRoundedRegular',
 },
 balanceDollarizedDivider: {
  width: 18,
  alignItems: 'center',
  justifyContent: 'center',
  gap: 2,
 },
 balanceDollarizedDividerDot: {
  width: 1,
  height: 3,
  backgroundColor: COLORS.colorPrimaryIntLetter2,
  opacity: 0.8,
 },
 balanceDollarizedRate: {
  minWidth: 60,
  paddingRight: 4,
  textAlign: 'right',
  color: COLORS.colorPrimaryIntLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'ArialRoundedRegular',
 },
 balanceRealResultWrap: {
  flexDirection: 'row',
  alignItems: 'center',
  marginLeft: 12,
  marginRight: 20,
  marginBottom: 12,
 },
 balanceRealResultLabel: {
  flex: 1.1,
  textAlign: 'right',
  color: COLORS.colorPrimaryIntLetter,
  fontSize: 16,
  fontFamily: 'OpenSansLight',
 },
 balanceRealResultValueWrap: {
  width: 108,
  minHeight: 40,
  justifyContent: 'center',
  marginRight: 16,
 },
 balanceRealResultValue: {
  textAlign: 'right',
  paddingRight: 4,
  color: COLORS.colorPrimaryClearLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'ArialRoundedRegular',
 },
 balancePartnersList: {
  marginTop: 8,
  marginBottom: 20,
 },
 balancePartnerCardWrap: {
  marginTop: 4,
  marginBottom: 4,
 },
 balancePartnerCard: {
  minHeight: 55,
  flexDirection: 'row',
  alignItems: 'center',
  paddingLeft: 12,
  paddingRight: 12,
  backgroundColor: COLORS.white,
  borderRadius: 8,
 },
 balancePartnerNameBlock: {
  flex: 1,
  paddingRight: 4,
 },
 balancePartnerName: {
  color: COLORS.colorPrimaryIntLetter2,
  fontSize: 16,
  fontFamily: 'OpenSansRegular',
 },
 balancePartnerSurname: {
  color: COLORS.colorPrimaryClearLetter,
  fontSize: 16,
  fontFamily: 'OpenSansLight',
 },
 balancePartnerAmountBlock: {
  width: 105,
  minHeight: 50,
  alignItems: 'center',
  justifyContent: 'center',
 },
 balancePartnerAmount: {
  textAlign: 'center',
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 balancePartnerPercentageBlock: {
  width: 55,
  minHeight: 50,
  marginLeft: 8,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
 },
 balancePartnerPercentage: {
  textAlign: 'center',
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 balancePartnerPercentSign: {
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 balancePartnerStateBlock: {
  width: 50,
  minHeight: 50,
  marginLeft: 8,
  alignItems: 'center',
  justifyContent: 'center',
 },
 balancePartnerStateIcon: {
  width: 25,
  height: 25,
  resizeMode: 'contain',
 },
 balancePartnerAssignedIcon: {
  opacity: 0.3,
 },
 balancePartnerPendingIcon: {
  opacity: 0.6,
 },
 balancePartnerAssignedValue: {
  color: COLORS.colorPrimaryIntLetter2,
 },
 balancePartnerPendingValue: {
  color: COLORS.colorPrimaryDarkLetter,
 },
 balancePartnersEmptyWrap: {
  marginTop: 8,
  marginBottom: 20,
  alignItems: 'center',
  justifyContent: 'center',
 },
 balancePartnersEmptyText: {
  color: COLORS.word_clear,
  fontSize: 15,
  fontFamily: 'OpenSansRegular',
 },
 balanceDivisionDialogBackdrop: {
  backgroundColor: 'rgba(0,0,0,0.52)',
  paddingHorizontal: 8,
 },
 balanceDivisionDialogCard: {
  width: '90%',
  backgroundColor: COLORS.background_dialog,
  borderRadius: 10,
  margin: 18,
  paddingTop: DIMENS.dialogMarginTop,
  paddingBottom: DIMENS.dialogMarginBottom,
  paddingLeft: DIMENS.dialogMarginLeft,
  paddingRight: DIMENS.dialogMarginRight,
 },
 balanceDivisionDialogMessageRow: {
  width: '100%',
  marginTop: 12,
  marginBottom: 8,
  flexDirection: 'row',
  alignItems: 'flex-start',
 },
 balanceDivisionDialogTitle: {
  color: COLORS.word,
  fontSize: 18,
  fontFamily: 'OpenSansRegular',
  textAlign: 'left',
 },
 balanceDivisionDialogActions: {
  marginTop: 22,
  flexDirection: 'row',
  alignItems: 'center',
 },
 balanceDivisionDialogCancelBtn: {
  flex: 1,
  minHeight: 42,
  alignItems: 'center',
  justifyContent: 'center',
 },
 balanceDivisionDialogCancelText: {
  color: COLORS.colorDialogButton,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 balanceDivisionDialogAcceptBtn: {
  flex: 1.1,
  minHeight: DIMENS.heightButton,
  borderRadius: DIMENS.buttonRadius,
  backgroundColor: COLORS.colorDialogButton,
  alignItems: 'center',
  justifyContent: 'center',
 },
 balanceDivisionDialogAcceptText: {
  color: COLORS.white,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 divisionAssignDialogAmountRow: {
  width: '100%',
  alignItems: 'center',
  justifyContent: 'center',
  marginTop: 4,
  marginBottom: 18,
 },
 divisionAssignDialogAmountText: {
  color: COLORS.word,
  fontSize: 28,
  fontFamily: 'OpenSansRegular',
  textAlign: 'center',
 },
 divisionAssignDialogMessageWrap: {
  width: '100%',
  marginBottom: 6,
 },
 divisionAssignDialogMessageText: {
  color: COLORS.colorPrimaryIntLetter,
  fontSize: 18,
  lineHeight: 28,
  fontFamily: 'OpenSansLight',
  textAlign: 'left',
 },
 divisionAssignDialogPartnerName: {
  marginTop: 10,
  color: COLORS.word,
  fontSize: 20,
  lineHeight: 30,
  fontFamily: 'OpenSansRegular',
  textAlign: 'left',
 },
 divisionScreen: {
  flex: 1,
  backgroundColor: COLORS.background,
 },
 divisionResultBar: {
  height: 55,
  backgroundColor: COLORS.background_violet,
  paddingLeft: 16,
  paddingRight: 16,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
 },
 divisionResultLabel: {
  color: COLORS.white,
  flex: 1,
  fontSize: 18,
  fontFamily: 'OpenSansRegular',
 },
 divisionResultValue: {
  color: COLORS.white,
  fontSize: 20,
  fontFamily: 'OpenSansRegular',
 },
 divisionResultCurrency: {
  marginRight: 8,
  color: COLORS.white,
  fontSize: 18,
  fontFamily: 'OpenSansRegular',
 },
 divisionDateBar: {
  backgroundColor: COLORS.background_violet_clear,
  justifyContent: 'center',
  paddingTop: 2,
  paddingBottom: 2,
  paddingLeft: 4,
  paddingRight: 8,
 },
 divisionDateText: {
  color: COLORS.word_clear,
  fontSize: 16,
  fontFamily: 'OpenSansRegular',
 },
 divisionListWrap: {
  flex: 1,
 },
 divisionListContent: {
  paddingTop: 4,
  paddingBottom: 80,
 },
 divisionPartnerCardWrap: {
  marginLeft: 4,
  marginRight: 4,
 },
 divisionPartnerCard: {
  marginTop: 4,
  marginBottom: 4,
  backgroundColor: COLORS.white,
  borderRadius: 8,
  paddingTop: 6,
  paddingBottom: 6,
  paddingLeft: 12,
  paddingRight: 12,
  flexDirection: 'row',
  alignItems: 'center',
 },
 divisionPartnerNameBlock: {
  flex: 1,
  paddingRight: 4,
 },
 divisionPartnerName: {
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: 17,
  fontFamily: 'OpenSansRegular',
 },
 divisionPartnerSurname: {
  marginTop: 0,
  color: COLORS.colorPrimaryClearLetter,
  fontSize: DIMENS.smallText,
  fontFamily: 'OpenSansRegular',
 },
 divisionPartnerAmountBox: {
  width: 105,
  height: 44,
  borderRadius: 8,
  backgroundColor: COLORS.background2,
  alignItems: 'center',
  justifyContent: 'center',
 },
 divisionPartnerAmountText: {
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
 },
 divisionPartnerPercentBox: {
  width: 60,
  height: 44,
  borderRadius: 8,
  marginLeft: 8,
  backgroundColor: COLORS.background2,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
 },
 divisionPartnerPercentText: {
  color: COLORS.word,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
 },
 divisionPartnerPercentSign: {
  marginLeft: 0,
  color: COLORS.word,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansLight',
 },
 divisionPartnerStateWrap: {
  marginLeft: 12,
  paddingLeft: 4,
  alignItems: 'center',
  justifyContent: 'center',
 },
 divisionPartnerStateDone: {
  width: 35,
  height: 35,
  position: 'relative',
  alignItems: 'center',
  justifyContent: 'center',
 },
 divisionPartnerStateDoneBase: {
  position: 'absolute',
  width: 35,
  height: 35,
  tintColor: COLORS.green_selected,
  resizeMode: 'contain',
 },
 divisionPartnerStateDoneIcon: {
  width: 22,
  height: 22,
  resizeMode: 'contain',
 },
 divisionPartnerStatePendingIcon: {
  width: 35,
  height: 35,
  opacity: 0.6,
  resizeMode: 'contain',
 },
 divisionBottomBar: {
  position: 'absolute',
  left: 12,
  right: 12,
  bottom: 24,
 },
 divisionDoneButton: {
  height: 45,
  borderRadius: 10,
  backgroundColor: COLORS.colorDialogButton,
  alignItems: 'center',
  justifyContent: 'center',
 },
 divisionDoneButtonText: {
  color: COLORS.white,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 createBalanceScreen: {
  flex: 1,
  backgroundColor: COLORS.background,
 },
 createBalanceHeaderBar: {
  height: 55,
  backgroundColor: COLORS.background_violet,
  justifyContent: 'center',
  paddingRight: 8,
 },
 createBalanceHeaderTopRow: {
  flexDirection: 'row',
  alignItems: 'center',
  marginLeft: 12,
  paddingTop: 2,
 },
 createBalanceHeaderBottomRow: {
  flexDirection: 'row',
  alignItems: 'center',
  marginLeft: 12,
  marginTop: -4,
  paddingTop: 6,
 },
 createBalanceHeaderMainLabel: {
  flex: 1.1,
  color: COLORS.white,
  fontSize: 16,
  fontFamily: 'OpenSansRegular',
  textAlign: 'right',
 },
 createBalanceHeaderMainLabelSecondary: {
  flex: 1.1,
  color: COLORS.white,
  fontSize: 16,
  fontFamily: 'OpenSansRegular',
  textAlign: 'right',
  paddingRight: 14,
 },
 createBalanceHeaderMainLabelRight: {
  color: COLORS.white,
  fontSize: 16,
  fontFamily: 'OpenSansRegular',
  textAlign: 'right',
  paddingLeft: 4,
  paddingRight: 8,
 },
 createBalanceHeaderSubLabel: {
  flex: 1.5,
  color: COLORS.white,
  fontSize: 12,
  fontFamily: 'OpenSansRegular',
  textAlign: 'right',
  paddingRight: 16,
 },
 createBalanceHeaderSubLabelRight: {
  color: COLORS.white,
  fontSize: 12,
  fontFamily: 'OpenSansRegular',
  textAlign: 'right',
  paddingLeft: 4,
  paddingRight: 8,
 },
 createBalanceHeaderBottomSpacer: {
  flex: 1.1,
  color: COLORS.transparent,
  textAlign: 'right',
 },
 createBalanceHeaderInvisibleDivider: {
  width: 1,
  marginLeft: 4,
  marginRight: 4,
  alignSelf: 'stretch',
  opacity: 0,
 },
 createBalanceDateBar: {
  backgroundColor: COLORS.background_violet_clear,
  paddingTop: 2,
  paddingBottom: 2,
  paddingLeft: 4,
  paddingRight: 8,
 },
 createBalanceDateText: {
  color: COLORS.word_clear,
  fontSize: 16,
  fontFamily: 'OpenSansRegular',
 },
 createBalanceLoadingWrap: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
  paddingHorizontal: 20,
 },
 createBalanceListContent: {
  paddingTop: 10,
  paddingBottom: 300,
 },
 createBalanceItemWrap: {
  paddingTop: 8,
  paddingBottom: 8,
 },
 createBalanceRow: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingLeft: 12,
  paddingRight: 12,
 },
 createBalanceCoinBlock: {
  width: 52,
  alignItems: 'center',
 },
 createBalanceValuesWrap: {
  flex: 1,
  marginLeft: 12,
  flexDirection: 'row',
  alignItems: 'center',
 },
 createBalanceFlag: {
  width: 35,
  height: 30,
  resizeMode: 'contain',
  marginBottom: 1,
 },
 createBalanceCode: {
  color: COLORS.colorPrimary,
  fontSize: 16,
  fontFamily: 'ArialRoundedRegular',
  textTransform: 'uppercase',
  textAlign: 'center',
 },
 createBalanceAmount: {
  flex: 0.98,
  textAlign: 'right',
  marginRight: 16,
  color: COLORS.colorPrimaryClearLetter,
  fontSize: DIMENS.bigText,
  fontFamily: 'ArialRoundedRegular',
 },
 createBalanceInputCard: {
  flex: 1.5,
  borderRadius: 6,
  backgroundColor: COLORS.white,
  flexDirection: 'row',
  alignItems: 'center',
  paddingTop: 4,
  paddingBottom: 4,
 },
 createBalanceInputLeft: {
  flex: 1.2,
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: 20,
  fontFamily: 'ArialRoundedRegular',
  textAlign: 'right',
  paddingRight: 4,
  paddingVertical: 3,
  includeFontPadding: false,
 },
 createBalanceDivider: {
  width: 1,
  alignItems: 'center',
  justifyContent: 'center',
  gap: 2,
  marginLeft: 4,
  marginRight: 4,
  alignSelf: 'stretch',
 },
 createBalanceDividerDot: {
  width: 1,
  flex: 1,
  backgroundColor: COLORS.colorPrimaryClearLetter,
  opacity: 0.8,
 },
 createBalanceInputRight: {
  width: 70,
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: 20,
  fontFamily: 'ArialRoundedRegular',
  textAlign: 'center',
  paddingVertical: 0,
  includeFontPadding: false,
 },
 createBalanceBottomPanel: {
  position: 'absolute',
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: COLORS.background,
 },
 createBalanceFooterWrap: {
  paddingTop: 6,
 },
 createBalanceFooterRow: {
  flexDirection: 'row',
  alignItems: 'flex-start',
  paddingLeft: 12,
  paddingRight: 12,
 },
 createBalanceFooterGhostCoinBlock: {
  width: 52,
  alignItems: 'flex-start',
 },
 createBalanceFooterGhostFlag: {
  width: 35,
  height: 30,
  opacity: 0,
 },
 createBalanceFooterGhostCode: {
  opacity: 0,
 },
 createBalanceTotalLabel: {
  width: 112,
  textAlign: 'right',
  marginRight: 16,
  color: COLORS.colorPrimaryClearLetter,
  fontSize: 20,
  fontFamily: 'ArialRoundedRegular',
 },
 createBalanceFooterValue: {
  flex: 1.2,
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: 20,
  fontFamily: 'ArialRoundedRegular',
  textAlign: 'right',
  paddingRight: 4,
  paddingVertical: 4,
  includeFontPadding: false,
 },
 createBalanceFooterValueRight: {
  width: 70,
 },
 createBalanceActionsRow: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: 12,
  marginLeft: 12,
  marginRight: 12,
  marginBottom: 24,
 },
 createBalanceCloseBtn: {
  minWidth: 0,
  height: 45,
  borderRadius: 10,
  backgroundColor: COLORS.colorDialogButton,
  alignItems: 'center',
  justifyContent: 'center',
  marginRight: 8,
  paddingHorizontal: 0,
 },
 createBalanceCloseText: {
  color: COLORS.white,
  width: 50,
  textAlign: 'center',
  fontSize: 18,
  fontFamily: 'OpenSansRegular',
 },
 createBalancePrimaryBtn: {
  flex: 1.15,
  height: 45,
  borderRadius: 10,
  backgroundColor: COLORS.colorDialogButton,
  alignItems: 'center',
  justifyContent: 'center',
  marginRight: 4,
 },
 createBalancePrimaryBtnWide: {
  flex: 1.2,
  height: 45,
  borderRadius: 10,
  backgroundColor: COLORS.colorDialogButton,
  alignItems: 'center',
  justifyContent: 'center',
  marginLeft: 4,
 },
 createBalancePrimaryText: {
  color: COLORS.white,
  fontSize: 16,
  fontFamily: 'OpenSansRegular',
  textAlign: 'center',
 },
 createBalanceEditDialogCard: {
  width: '92%',
  backgroundColor: COLORS.background_dialog,
  borderRadius: 10,
  margin: 8,
 },
 createBalanceEditDialogBody: {
  width: '100%',
  paddingTop: DIMENS.dialogMarginTop,
  paddingBottom: DIMENS.dialogMarginBottom,
  paddingLeft: DIMENS.dialogMarginLeft,
  paddingRight: DIMENS.dialogMarginRight,
 },
 createBalanceEditDialogAmountRow: {
  minHeight: 35,
  marginTop: 16,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
 },
 createBalanceEditDialogCurrency: {
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: 20,
  fontFamily: 'OpenSansRegular',
  textAlign: 'center',
  paddingLeft: 8,
 },
 createBalanceEditDialogAmountValue: {
  color: COLORS.colorPrimaryDarkLetter,
  fontSize: 20,
  fontFamily: 'OpenSansRegular',
  textAlign: 'center',
  paddingLeft: 8,
 },
 createBalanceEditDialogFishertonNote: {
  marginTop: 12,
  color: COLORS.colorPrimaryIntLetter2,
  fontSize: 20,
  fontFamily: 'OpenSansLight',
  lineHeight: 24,
 },
 createBalanceEditDialogInputCard: {
  marginTop: 12,
  minHeight: DIMENS.heightRecCuadInpunt,
  borderRadius: 8,
  backgroundColor: COLORS.white,
  flexDirection: 'row',
  alignItems: 'center',
  paddingLeft: 8,
  paddingRight: 0,
 },
 createBalanceEditDialogInputLabel: {
  flex: 2,
  color: COLORS.colorPrimaryIntLetter,
  fontSize: DIMENS.generalText,
  fontFamily: 'OpenSansRegular',
 },
 createBalanceEditDialogDivider: {
  width: 1,
  alignSelf: 'stretch',
  marginLeft: 4,
  marginTop: 2,
  marginBottom: 2,
  marginRight: 4,
  alignItems: 'center',
  justifyContent: 'center',
  gap: 2,
 },
 createBalanceEditDialogDividerDot: {
  width: 1,
  flex: 1,
  backgroundColor: COLORS.colorPrimaryClearLetter,
  opacity: 0.8,
 },
 createBalanceEditDialogInput: {
  flex: 2,
  height: 35,
  color: COLORS.word,
  fontSize: 20,
  fontFamily: 'OpenSansRegular',
  textAlign: 'left',
  paddingLeft: 8,
  paddingVertical: 0,
  includeFontPadding: false,
 },
 createBalanceEditDialogInputEndSpacer: {
  width: 20,
 },
 createBalanceEditDialogActions: {
  marginTop: 20,
  flexDirection: 'row',
  alignItems: 'center',
 },
 createBalanceEditDialogCancelBtn: {
  flex: 1,
  minHeight: 42,
  alignItems: 'center',
  justifyContent: 'center',
 },
 createBalanceEditDialogCancelText: {
  color: COLORS.colorDialogButton,
  fontSize: 18,
  fontFamily: 'OpenSansRegular',
 },
 createBalanceEditDialogSaveBtn: {
  flex: 1,
  minHeight: DIMENS.heightButton,
  borderRadius: 8,
  backgroundColor: COLORS.colorDialogButton,
  alignItems: 'center',
  justifyContent: 'center',
 },
 createBalanceEditDialogSaveText: {
  color: COLORS.white,
  fontSize: 18,
  fontFamily: 'OpenSansBold',
 },
});

export default styles;
